/// Question model for numeracy activities
/// 
/// Enhanced with support for curriculum metadata (ACARA, NAPLAN, Bloom's taxonomy)
/// via optional metadata field for Phase 7+ integration.
class NumeracyQuestion {
  final String id;
  final String skillId;
  final String question;
  final List<String> options;
  final int correctIndex;
  final String? hint;
  final String? explanation;
  final int difficulty; // 1-5
  final NumeracyQuestionType type;
  final String? imageAsset; // Optional visual for the question
  final dynamic metadata; // QuestionMetadata (optional for backwards compatibility)

  const NumeracyQuestion({
    required this.id,
    required this.skillId,
    required this.question,
    required this.options,
    required this.correctIndex,
    this.hint,
    this.explanation,
    this.difficulty = 1,
    this.type = NumeracyQuestionType.multipleChoice,
    this.imageAsset,
    this.metadata,
  });

  String get correctAnswer => options[correctIndex];

  bool isCorrect(int selectedIndex) => selectedIndex == correctIndex;
  
  /// Returns the difficulty as a double (0.0-5.0)
  double get difficultyValue => difficulty.toDouble();
}

/// Types of numeracy questions
enum NumeracyQuestionType {
  multipleChoice,
  counting,
  numberLine,
  visualMath,
  patternRecognition,
  dragAndDrop,
  tracing,
}

/// Question bank for counting skill (ages 4-6)
class CountingQuestions {
  static const List<NumeracyQuestion> questions = [
    // Level 1 - Counting to 10
    NumeracyQuestion(
      id: 'count_1',
      skillId: 'skill_counting',
      question: 'How many stars? ⭐⭐⭐',
      options: ['2', '3', '4', '5'],
      correctIndex: 1,
      hint: 'Count each star one by one',
      explanation: 'There are 3 stars! ⭐⭐⭐ = 1, 2, 3',
      difficulty: 1,
      type: NumeracyQuestionType.counting,
    ),
    NumeracyQuestion(
      id: 'count_2',
      skillId: 'skill_counting',
      question: 'How many apples? 🍎🍎🍎🍎🍎',
      options: ['3', '4', '5', '6'],
      correctIndex: 2,
      hint: 'Touch each apple as you count',
      explanation: 'There are 5 apples! Count: 1, 2, 3, 4, 5',
      difficulty: 1,
      type: NumeracyQuestionType.counting,
    ),
    NumeracyQuestion(
      id: 'count_3',
      skillId: 'skill_counting',
      question: 'What number comes after 5?',
      options: ['4', '5', '6', '7'],
      correctIndex: 2,
      hint: 'Count: 4, 5, ...',
      explanation: 'After 5 comes 6! The counting sequence is: 4, 5, 6, 7',
      difficulty: 1,
    ),
    NumeracyQuestion(
      id: 'count_4',
      skillId: 'skill_counting',
      question: 'How many fingers on one hand? 🖐️',
      options: ['3', '4', '5', '6'],
      correctIndex: 2,
      hint: 'Look at your own hand!',
      explanation: 'One hand has 5 fingers!',
      difficulty: 1,
      type: NumeracyQuestionType.counting,
    ),
    NumeracyQuestion(
      id: 'count_5',
      skillId: 'skill_counting',
      question: 'What number comes before 3?',
      options: ['1', '2', '3', '4'],
      correctIndex: 1,
      hint: 'Count backwards: 3, ...',
      explanation: 'Before 3 comes 2! The sequence is: 1, 2, 3',
      difficulty: 1,
    ),
    NumeracyQuestion(
      id: 'count_drag_1',
      skillId: 'skill_counting',
      question: 'Drag the number 5 to the box!',
      options: ['3', '5', '7', '9'],
      correctIndex: 1,
      hint: 'Look for the number that looks like 5',
      explanation: 'Great job! You found the number 5.',
      difficulty: 1,
      type: NumeracyQuestionType.dragAndDrop,
    ),
    NumeracyQuestion(
      id: 'trace_3',
      skillId: 'skill_counting',
      question: 'Trace the number 3!',
      options: ['3'], // The character to trace
      correctIndex: 0,
      hint: 'Follow the shape of the number',
      explanation: 'Excellent writing!',
      difficulty: 1,
      type: NumeracyQuestionType.tracing,
    ),
    // Level 2 - Counting to 20
    NumeracyQuestion(
      id: 'count_6',
      skillId: 'skill_counting',
      question: 'How many hearts?\n❤️❤️❤️❤️❤️❤️❤️❤️',
      options: ['6', '7', '8', '9'],
      correctIndex: 2,
      hint: 'Count carefully, there are quite a few!',
      explanation: 'There are 8 hearts!',
      difficulty: 2,
      type: NumeracyQuestionType.counting,
    ),
    NumeracyQuestion(
      id: 'count_7',
      skillId: 'skill_counting',
      question: 'What number comes after 9?',
      options: ['8', '9', '10', '11'],
      correctIndex: 2,
      hint: 'This is a special two-digit number!',
      explanation: 'After 9 comes 10! We write it with a 1 and a 0.',
      difficulty: 2,
    ),
    NumeracyQuestion(
      id: 'count_8',
      skillId: 'skill_counting',
      question: 'What number is between 14 and 16?',
      options: ['13', '14', '15', '17'],
      correctIndex: 2,
      hint: 'Count: 14, ?, 16',
      explanation: '15 is between 14 and 16! The sequence is 14, 15, 16.',
      difficulty: 2,
    ),
    NumeracyQuestion(
      id: 'count_9',
      skillId: 'skill_counting',
      question: 'Count by 2s: 2, 4, 6, ?',
      options: ['7', '8', '9', '10'],
      correctIndex: 1,
      hint: 'Add 2 to 6',
      explanation:
          'Counting by 2s: 2, 4, 6, 8, 10! We skip a number each time.',
      difficulty: 2,
    ),
    NumeracyQuestion(
      id: 'count_10',
      skillId: 'skill_counting',
      question: 'How many 🌟 in two rows?\n🌟🌟🌟🌟🌟\n🌟🌟🌟🌟🌟',
      options: ['8', '9', '10', '11'],
      correctIndex: 2,
      hint: '5 + 5 = ?',
      explanation: '5 stars + 5 stars = 10 stars total!',
      difficulty: 2,
      type: NumeracyQuestionType.counting,
    ),
    // Level 3 - Counting patterns
    NumeracyQuestion(
      id: 'count_11',
      skillId: 'skill_counting',
      question: 'Count by 5s: 5, 10, 15, ?',
      options: ['16', '18', '20', '25'],
      correctIndex: 2,
      hint: 'Add 5 to 15',
      explanation: 'Counting by 5s: 5, 10, 15, 20, 25! Add 5 each time.',
      difficulty: 3,
    ),
    NumeracyQuestion(
      id: 'count_12',
      skillId: 'skill_counting',
      question: 'Count backwards: 10, 9, 8, ?',
      options: ['5', '6', '7', '9'],
      correctIndex: 2,
      hint: 'Subtract 1 from 8',
      explanation: 'Counting backwards: 10, 9, 8, 7! Subtract 1 each time.',
      difficulty: 3,
    ),
    NumeracyQuestion(
      id: 'count_13',
      skillId: 'skill_counting',
      question: 'Count by 10s: 10, 20, 30, ?',
      options: ['31', '35', '40', '50'],
      correctIndex: 2,
      hint: 'Add 10 to 30',
      explanation: 'Counting by 10s: 10, 20, 30, 40, 50! Add 10 each time.',
      difficulty: 3,
    ),
  ];

  static List<NumeracyQuestion> getByDifficulty(int level) {
    return questions.where((q) => q.difficulty <= level).toList();
  }
}

/// Question bank for addition skill (ages 5-8)
class AdditionQuestions {
  static const List<NumeracyQuestion> questions = [
    // Level 1 - Adding within 10
    NumeracyQuestion(
      id: 'add_1',
      skillId: 'skill_addition',
      question: '2 + 3 = ?',
      options: ['4', '5', '6', '7'],
      correctIndex: 1,
      hint: 'Start at 2 and count 3 more',
      explanation: '2 + 3 = 5. Start at 2, then count: 3, 4, 5!',
      difficulty: 1,
    ),
    NumeracyQuestion(
      id: 'add_2',
      skillId: 'skill_addition',
      question: '🍎🍎 + 🍎🍎🍎 = ?',
      options: ['4', '5', '6', '7'],
      correctIndex: 1,
      hint: 'Count all the apples together',
      explanation: '2 apples + 3 apples = 5 apples total!',
      difficulty: 1,
      type: NumeracyQuestionType.visualMath,
    ),
    NumeracyQuestion(
      id: 'add_3',
      skillId: 'skill_addition',
      question: '4 + 1 = ?',
      options: ['3', '4', '5', '6'],
      correctIndex: 2,
      hint: 'One more than 4',
      explanation: '4 + 1 = 5. Adding 1 gives you the next number!',
      difficulty: 1,
    ),
    NumeracyQuestion(
      id: 'add_4',
      skillId: 'skill_addition',
      question: '1 + 1 = ?',
      options: ['1', '2', '3', '4'],
      correctIndex: 1,
      hint: 'Count: 1 and 1 more',
      explanation: '1 + 1 = 2. The simplest addition!',
      difficulty: 1,
    ),
    NumeracyQuestion(
      id: 'add_5',
      skillId: 'skill_addition',
      question: '5 + 0 = ?',
      options: ['0', '4', '5', '6'],
      correctIndex: 2,
      hint: 'Adding zero doesn\'t change the number',
      explanation: '5 + 0 = 5. Adding zero keeps the number the same!',
      difficulty: 1,
    ),
    // Level 2 - Adding within 20
    NumeracyQuestion(
      id: 'add_6',
      skillId: 'skill_addition',
      question: '7 + 5 = ?',
      options: ['10', '11', '12', '13'],
      correctIndex: 2,
      hint: 'Try making 10 first: 7 + 3 = 10, then add 2 more',
      explanation: '7 + 5 = 12. You can count on or make a 10!',
      difficulty: 2,
    ),
    NumeracyQuestion(
      id: 'add_7',
      skillId: 'skill_addition',
      question: '8 + 6 = ?',
      options: ['12', '13', '14', '15'],
      correctIndex: 2,
      hint: '8 + 2 = 10, then add 4 more',
      explanation: '8 + 6 = 14. Making 10 helps: 8 + 2 = 10, 10 + 4 = 14!',
      difficulty: 2,
    ),
    NumeracyQuestion(
      id: 'add_8',
      skillId: 'skill_addition',
      question: '9 + 9 = ?',
      options: ['16', '17', '18', '19'],
      correctIndex: 2,
      hint: 'Double 9!',
      explanation: '9 + 9 = 18. This is a doubles fact!',
      difficulty: 2,
    ),
    NumeracyQuestion(
      id: 'add_9',
      skillId: 'skill_addition',
      question: '10 + 6 = ?',
      options: ['14', '15', '16', '17'],
      correctIndex: 2,
      hint: 'Adding to 10 is easy - just put them together!',
      explanation: '10 + 6 = 16. Adding to 10 gives us teen numbers!',
      difficulty: 2,
    ),
    // Level 3 - Adding larger numbers
    NumeracyQuestion(
      id: 'add_10',
      skillId: 'skill_addition',
      question: '15 + 8 = ?',
      options: ['21', '22', '23', '24'],
      correctIndex: 2,
      hint: '15 + 5 = 20, then add 3 more',
      explanation: '15 + 8 = 23. Break it up: 15 + 5 = 20, 20 + 3 = 23!',
      difficulty: 3,
    ),
    NumeracyQuestion(
      id: 'add_11',
      skillId: 'skill_addition',
      question: '24 + 13 = ?',
      options: ['35', '36', '37', '38'],
      correctIndex: 2,
      hint: 'Add the tens: 20 + 10 = 30. Add the ones: 4 + 3 = 7',
      explanation: '24 + 13 = 37. Add tens and ones separately!',
      difficulty: 3,
    ),
    NumeracyQuestion(
      id: 'add_12',
      skillId: 'skill_addition',
      question: '35 + 27 = ?',
      options: ['52', '62', '63', '72'],
      correctIndex: 1,
      hint: '30 + 20 = 50, 5 + 7 = 12, 50 + 12 = ?',
      explanation: '35 + 27 = 62. Add tens: 50, add ones: 12, total: 62!',
      difficulty: 3,
    ),
  ];

  static List<NumeracyQuestion> getByDifficulty(int level) {
    return questions.where((q) => q.difficulty <= level).toList();
  }
}

/// Question bank for subtraction skill (ages 5-8)
class SubtractionQuestions {
  static const List<NumeracyQuestion> questions = [
    // Level 1 - Subtracting within 10
    NumeracyQuestion(
      id: 'sub_1',
      skillId: 'skill_subtraction',
      question: '5 - 2 = ?',
      options: ['2', '3', '4', '5'],
      correctIndex: 1,
      hint: 'Start at 5 and count back 2',
      explanation: '5 - 2 = 3. Count back: 5, 4, 3!',
      difficulty: 1,
    ),
    NumeracyQuestion(
      id: 'sub_2',
      skillId: 'skill_subtraction',
      question: '🍪🍪🍪🍪🍪 - 🍪🍪 = ?',
      options: ['2', '3', '4', '5'],
      correctIndex: 1,
      hint: 'Take away 2 cookies from 5',
      explanation: '5 cookies - 2 cookies = 3 cookies left!',
      difficulty: 1,
      type: NumeracyQuestionType.visualMath,
    ),
    NumeracyQuestion(
      id: 'sub_3',
      skillId: 'skill_subtraction',
      question: '7 - 1 = ?',
      options: ['5', '6', '7', '8'],
      correctIndex: 1,
      hint: 'One less than 7',
      explanation: '7 - 1 = 6. Subtracting 1 gives the number before!',
      difficulty: 1,
    ),
    NumeracyQuestion(
      id: 'sub_4',
      skillId: 'skill_subtraction',
      question: '4 - 0 = ?',
      options: ['0', '3', '4', '5'],
      correctIndex: 2,
      hint: 'Taking away nothing changes nothing!',
      explanation: '4 - 0 = 4. Subtracting zero keeps the number the same!',
      difficulty: 1,
    ),
    NumeracyQuestion(
      id: 'sub_5',
      skillId: 'skill_subtraction',
      question: '6 - 6 = ?',
      options: ['0', '1', '6', '12'],
      correctIndex: 0,
      hint: 'Any number minus itself equals...',
      explanation: '6 - 6 = 0. Taking away all leaves nothing!',
      difficulty: 1,
    ),
    // Level 2 - Subtracting within 20
    NumeracyQuestion(
      id: 'sub_6',
      skillId: 'skill_subtraction',
      question: '12 - 5 = ?',
      options: ['5', '6', '7', '8'],
      correctIndex: 2,
      hint: 'Count back from 12: 11, 10, 9, 8, 7',
      explanation: '12 - 5 = 7. You can count back or think: 5 + ? = 12',
      difficulty: 2,
    ),
    NumeracyQuestion(
      id: 'sub_7',
      skillId: 'skill_subtraction',
      question: '15 - 8 = ?',
      options: ['5', '6', '7', '8'],
      correctIndex: 2,
      hint: '15 - 5 = 10, then subtract 3 more',
      explanation: '15 - 8 = 7. Break it up: 15 - 5 = 10, 10 - 3 = 7!',
      difficulty: 2,
    ),
    NumeracyQuestion(
      id: 'sub_8',
      skillId: 'skill_subtraction',
      question: '18 - 9 = ?',
      options: ['7', '8', '9', '10'],
      correctIndex: 2,
      hint: 'Half of 18!',
      explanation: '18 - 9 = 9. This is a doubles fact in reverse!',
      difficulty: 2,
    ),
    NumeracyQuestion(
      id: 'sub_9',
      skillId: 'skill_subtraction',
      question: '16 - 7 = ?',
      options: ['7', '8', '9', '10'],
      correctIndex: 2,
      hint: '16 - 6 = 10, then subtract 1 more',
      explanation: '16 - 7 = 9. Make a 10: 16 - 6 = 10, 10 - 1 = 9!',
      difficulty: 2,
    ),
    // Level 3 - Larger numbers
    NumeracyQuestion(
      id: 'sub_10',
      skillId: 'skill_subtraction',
      question: '25 - 12 = ?',
      options: ['11', '12', '13', '14'],
      correctIndex: 2,
      hint: 'Subtract tens: 20 - 10 = 10. Subtract ones: 5 - 2 = 3',
      explanation: '25 - 12 = 13. Subtract tens and ones separately!',
      difficulty: 3,
    ),
    NumeracyQuestion(
      id: 'sub_11',
      skillId: 'skill_subtraction',
      question: '43 - 18 = ?',
      options: ['23', '24', '25', '26'],
      correctIndex: 2,
      hint: '43 - 20 = 23, then add 2 back (since we took 2 extra)',
      explanation: '43 - 18 = 25. Use friendly numbers: 43 - 20 + 2 = 25!',
      difficulty: 3,
    ),
    NumeracyQuestion(
      id: 'sub_12',
      skillId: 'skill_subtraction',
      question: '50 - 27 = ?',
      options: ['21', '22', '23', '24'],
      correctIndex: 2,
      hint: '50 - 30 = 20, then add 3 back',
      explanation: '50 - 27 = 23. Round to 30: 50 - 30 = 20, 20 + 3 = 23!',
      difficulty: 3,
    ),
  ];

  static List<NumeracyQuestion> getByDifficulty(int level) {
    return questions.where((q) => q.difficulty <= level).toList();
  }
}

/// Question bank for multiplication skill (ages 7-10)
class MultiplicationQuestions {
  static const List<NumeracyQuestion> questions = [
    // Level 1 - 2s, 5s, 10s tables
    NumeracyQuestion(
      id: 'mult_1',
      skillId: 'skill_multiplication',
      question: '2 × 3 = ?',
      options: ['5', '6', '7', '8'],
      correctIndex: 1,
      hint: '2 + 2 + 2 = ?',
      explanation: '2 × 3 = 6. That\'s 3 groups of 2: 2 + 2 + 2 = 6!',
      difficulty: 1,
    ),
    NumeracyQuestion(
      id: 'mult_2',
      skillId: 'skill_multiplication',
      question: '5 × 2 = ?',
      options: ['7', '8', '9', '10'],
      correctIndex: 3,
      hint: 'Count by 5s twice: 5, 10',
      explanation: '5 × 2 = 10. Two groups of 5: 5 + 5 = 10!',
      difficulty: 1,
    ),
    NumeracyQuestion(
      id: 'mult_3',
      skillId: 'skill_multiplication',
      question: '10 × 3 = ?',
      options: ['13', '20', '30', '40'],
      correctIndex: 2,
      hint: 'Count by 10s: 10, 20, 30',
      explanation: '10 × 3 = 30. Three 10s make 30!',
      difficulty: 1,
    ),
    NumeracyQuestion(
      id: 'mult_4',
      skillId: 'skill_multiplication',
      question: '2 × 5 = ?',
      options: ['7', '8', '9', '10'],
      correctIndex: 3,
      hint: 'Same as 5 × 2!',
      explanation: '2 × 5 = 10. Multiplication works both ways!',
      difficulty: 1,
    ),
    NumeracyQuestion(
      id: 'mult_5',
      skillId: 'skill_multiplication',
      question: '1 × 7 = ?',
      options: ['1', '6', '7', '8'],
      correctIndex: 2,
      hint: 'One group of 7',
      explanation: '1 × 7 = 7. Any number times 1 equals itself!',
      difficulty: 1,
    ),
    // Level 2 - 3s, 4s tables
    NumeracyQuestion(
      id: 'mult_6',
      skillId: 'skill_multiplication',
      question: '3 × 4 = ?',
      options: ['10', '11', '12', '13'],
      correctIndex: 2,
      hint: '3 + 3 + 3 + 3 = ?',
      explanation: '3 × 4 = 12. Four groups of 3: 3 + 3 + 3 + 3 = 12!',
      difficulty: 2,
    ),
    NumeracyQuestion(
      id: 'mult_7',
      skillId: 'skill_multiplication',
      question: '4 × 5 = ?',
      options: ['16', '18', '20', '22'],
      correctIndex: 2,
      hint: 'Count by 4s five times, or by 5s four times',
      explanation: '4 × 5 = 20. That\'s half of 4 × 10!',
      difficulty: 2,
    ),
    NumeracyQuestion(
      id: 'mult_8',
      skillId: 'skill_multiplication',
      question: '6 × 2 = ?',
      options: ['10', '11', '12', '14'],
      correctIndex: 2,
      hint: 'Double 6!',
      explanation: '6 × 2 = 12. Multiplying by 2 is the same as doubling!',
      difficulty: 2,
    ),
    NumeracyQuestion(
      id: 'mult_9',
      skillId: 'skill_multiplication',
      question: '7 × 3 = ?',
      options: ['18', '19', '20', '21'],
      correctIndex: 3,
      hint: '7 + 7 + 7 = ?',
      explanation: '7 × 3 = 21. Three 7s: 7 + 7 + 7 = 21!',
      difficulty: 2,
    ),
    // Level 3 - 6s, 7s, 8s, 9s tables
    NumeracyQuestion(
      id: 'mult_10',
      skillId: 'skill_multiplication',
      question: '6 × 6 = ?',
      options: ['32', '34', '36', '38'],
      correctIndex: 2,
      hint: 'A square number!',
      explanation: '6 × 6 = 36. Six groups of six!',
      difficulty: 3,
    ),
    NumeracyQuestion(
      id: 'mult_11',
      skillId: 'skill_multiplication',
      question: '7 × 8 = ?',
      options: ['54', '55', '56', '57'],
      correctIndex: 2,
      hint: '5, 6, 7, 8 → 56 = 7 × 8',
      explanation: '7 × 8 = 56. A tricky one! Remember: 56 = 7 × 8!',
      difficulty: 3,
    ),
    NumeracyQuestion(
      id: 'mult_12',
      skillId: 'skill_multiplication',
      question: '9 × 7 = ?',
      options: ['61', '62', '63', '64'],
      correctIndex: 2,
      hint: '10 × 7 = 70, subtract 7',
      explanation: '9 × 7 = 63. Use the 10s trick: 70 - 7 = 63!',
      difficulty: 3,
    ),
    NumeracyQuestion(
      id: 'mult_13',
      skillId: 'skill_multiplication',
      question: '8 × 8 = ?',
      options: ['62', '64', '66', '68'],
      correctIndex: 1,
      hint: 'Another square number!',
      explanation: '8 × 8 = 64. Eight eights are sixty-four!',
      difficulty: 3,
    ),
    NumeracyQuestion(
      id: 'mult_14',
      skillId: 'skill_multiplication',
      question: '9 × 9 = ?',
      options: ['79', '80', '81', '82'],
      correctIndex: 2,
      hint: 'The largest single-digit square!',
      explanation: '9 × 9 = 81. Nine nines are eighty-one!',
      difficulty: 3,
    ),
  ];

  static List<NumeracyQuestion> getByDifficulty(int level) {
    return questions.where((q) => q.difficulty <= level).toList();
  }
}

/// Question bank for number patterns skill (ages 6-10)
class PatternQuestions {
  static const List<NumeracyQuestion> questions = [
    // Level 1 - Simple patterns
    NumeracyQuestion(
      id: 'pat_1',
      skillId: 'skill_patterns',
      question: 'What comes next? 1, 2, 3, 4, ?',
      options: ['4', '5', '6', '7'],
      correctIndex: 1,
      hint: 'Add 1 each time',
      explanation: 'The pattern adds 1 each time. Next is 5!',
      difficulty: 1,
      type: NumeracyQuestionType.patternRecognition,
    ),
    NumeracyQuestion(
      id: 'pat_2',
      skillId: 'skill_patterns',
      question: 'What comes next? 2, 4, 6, 8, ?',
      options: ['9', '10', '11', '12'],
      correctIndex: 1,
      hint: 'Skip counting by 2s',
      explanation: 'The pattern adds 2 each time. 8 + 2 = 10!',
      difficulty: 1,
      type: NumeracyQuestionType.patternRecognition,
    ),
    NumeracyQuestion(
      id: 'pat_3',
      skillId: 'skill_patterns',
      question: 'What comes next? 5, 10, 15, 20, ?',
      options: ['21', '22', '25', '30'],
      correctIndex: 2,
      hint: 'Skip counting by 5s',
      explanation: 'The pattern adds 5 each time. 20 + 5 = 25!',
      difficulty: 1,
      type: NumeracyQuestionType.patternRecognition,
    ),
    NumeracyQuestion(
      id: 'pat_4',
      skillId: 'skill_patterns',
      question: 'What comes next? 10, 20, 30, 40, ?',
      options: ['45', '50', '55', '60'],
      correctIndex: 1,
      hint: 'Skip counting by 10s',
      explanation: 'The pattern adds 10 each time. 40 + 10 = 50!',
      difficulty: 1,
      type: NumeracyQuestionType.patternRecognition,
    ),
    // Level 2 - More complex patterns
    NumeracyQuestion(
      id: 'pat_5',
      skillId: 'skill_patterns',
      question: 'What comes next? 1, 3, 5, 7, ?',
      options: ['8', '9', '10', '11'],
      correctIndex: 1,
      hint: 'Odd numbers!',
      explanation: 'These are odd numbers. Add 2 to get 9!',
      difficulty: 2,
      type: NumeracyQuestionType.patternRecognition,
    ),
    NumeracyQuestion(
      id: 'pat_6',
      skillId: 'skill_patterns',
      question: 'What comes next? 10, 9, 8, 7, ?',
      options: ['5', '6', '7', '8'],
      correctIndex: 1,
      hint: 'Counting backwards!',
      explanation: 'The pattern subtracts 1 each time. 7 - 1 = 6!',
      difficulty: 2,
      type: NumeracyQuestionType.patternRecognition,
    ),
    NumeracyQuestion(
      id: 'pat_7',
      skillId: 'skill_patterns',
      question: 'What comes next? 2, 4, 8, 16, ?',
      options: ['18', '24', '30', '32'],
      correctIndex: 3,
      hint: 'Each number doubles!',
      explanation: 'The pattern doubles each time. 16 × 2 = 32!',
      difficulty: 2,
      type: NumeracyQuestionType.patternRecognition,
    ),
    NumeracyQuestion(
      id: 'pat_8',
      skillId: 'skill_patterns',
      question: 'What comes next? 1, 4, 9, 16, ?',
      options: ['20', '23', '25', '27'],
      correctIndex: 2,
      hint: 'These are square numbers: 1², 2², 3², 4², ?²',
      explanation: '1, 4, 9, 16, 25 are squares: 1×1, 2×2, 3×3, 4×4, 5×5!',
      difficulty: 2,
      type: NumeracyQuestionType.patternRecognition,
    ),
    // Level 3 - Advanced patterns
    NumeracyQuestion(
      id: 'pat_9',
      skillId: 'skill_patterns',
      question: 'What comes next? 1, 1, 2, 3, 5, 8, ?',
      options: ['10', '11', '12', '13'],
      correctIndex: 3,
      hint: 'Add the two previous numbers!',
      explanation: 'This is the Fibonacci sequence! 5 + 8 = 13',
      difficulty: 3,
      type: NumeracyQuestionType.patternRecognition,
    ),
    NumeracyQuestion(
      id: 'pat_10',
      skillId: 'skill_patterns',
      question: 'What comes next? 3, 6, 12, 24, ?',
      options: ['36', '42', '48', '50'],
      correctIndex: 2,
      hint: 'Each number doubles!',
      explanation: 'The pattern doubles each time. 24 × 2 = 48!',
      difficulty: 3,
      type: NumeracyQuestionType.patternRecognition,
    ),
    NumeracyQuestion(
      id: 'pat_11',
      skillId: 'skill_patterns',
      question: 'What comes next? 100, 90, 80, 70, ?',
      options: ['50', '55', '60', '65'],
      correctIndex: 2,
      hint: 'Subtract 10 each time',
      explanation: 'The pattern subtracts 10 each time. 70 - 10 = 60!',
      difficulty: 3,
      type: NumeracyQuestionType.patternRecognition,
    ),
    NumeracyQuestion(
      id: 'pat_12',
      skillId: 'skill_patterns',
      question: 'What comes next? 1, 2, 4, 7, 11, ?',
      options: ['14', '15', '16', '17'],
      correctIndex: 2,
      hint: 'The gap increases: +1, +2, +3, +4, +?',
      explanation:
          'Add increasing amounts: 1+1=2, 2+2=4, 4+3=7, 7+4=11, 11+5=16!',
      difficulty: 3,
      type: NumeracyQuestionType.patternRecognition,
    ),
  ];

  static List<NumeracyQuestion> getByDifficulty(int level) {
    return questions.where((q) => q.difficulty <= level).toList();
  }
}

/// Question bank for place value skill (ages 6-9)
class PlaceValueQuestions {
  static const List<NumeracyQuestion> questions = [
    // Level 1 - Tens and ones
    NumeracyQuestion(
      id: 'pv_1',
      skillId: 'skill_place_value',
      question: 'In the number 23, what digit is in the tens place?',
      options: ['2', '3', '23', '5'],
      correctIndex: 0,
      hint: 'The tens place is on the left',
      explanation:
          'In 23, the 2 is in the tens place (worth 20) and 3 is in the ones place.',
      difficulty: 1,
    ),
    NumeracyQuestion(
      id: 'pv_2',
      skillId: 'skill_place_value',
      question: 'In the number 45, what digit is in the ones place?',
      options: ['4', '5', '45', '9'],
      correctIndex: 1,
      hint: 'The ones place is on the right',
      explanation:
          'In 45, the 5 is in the ones place (worth 5) and 4 is in the tens place.',
      difficulty: 1,
    ),
    NumeracyQuestion(
      id: 'pv_3',
      skillId: 'skill_place_value',
      question: 'What is 30 + 7?',
      options: ['10', '37', '73', '307'],
      correctIndex: 1,
      hint: '3 tens and 7 ones',
      explanation: '30 + 7 = 37. Three tens plus seven ones equals 37!',
      difficulty: 1,
    ),
    NumeracyQuestion(
      id: 'pv_4',
      skillId: 'skill_place_value',
      question: 'How many tens are in 60?',
      options: ['0', '6', '60', '600'],
      correctIndex: 1,
      hint: '60 = ? × 10',
      explanation: '60 has 6 tens. 6 × 10 = 60!',
      difficulty: 1,
    ),
    // Level 2 - Hundreds
    NumeracyQuestion(
      id: 'pv_5',
      skillId: 'skill_place_value',
      question: 'In the number 256, what digit is in the hundreds place?',
      options: ['2', '5', '6', '256'],
      correctIndex: 0,
      hint: 'The hundreds place is furthest left',
      explanation: 'In 256, the 2 is in the hundreds place (worth 200).',
      difficulty: 2,
    ),
    NumeracyQuestion(
      id: 'pv_6',
      skillId: 'skill_place_value',
      question: 'What is 300 + 40 + 8?',
      options: ['3408', '348', '3048', '384'],
      correctIndex: 1,
      hint: '3 hundreds, 4 tens, 8 ones',
      explanation: '300 + 40 + 8 = 348. Three hundreds, four tens, eight ones!',
      difficulty: 2,
    ),
    NumeracyQuestion(
      id: 'pv_7',
      skillId: 'skill_place_value',
      question: 'What is the value of the 5 in 527?',
      options: ['5', '50', '500', '5000'],
      correctIndex: 2,
      hint: 'The 5 is in the hundreds place',
      explanation:
          'In 527, the 5 is in the hundreds place, so its value is 500!',
      difficulty: 2,
    ),
    NumeracyQuestion(
      id: 'pv_8',
      skillId: 'skill_place_value',
      question: 'Which number has 4 hundreds, 0 tens, and 3 ones?',
      options: ['43', '304', '403', '430'],
      correctIndex: 2,
      hint: '4 in hundreds, 0 in tens, 3 in ones',
      explanation: '4 hundreds, 0 tens, 3 ones = 403!',
      difficulty: 2,
    ),
    // Level 3 - Thousands
    NumeracyQuestion(
      id: 'pv_9',
      skillId: 'skill_place_value',
      question: 'In 3,456, what is the value of the 4?',
      options: ['4', '40', '400', '4000'],
      correctIndex: 2,
      hint: 'The 4 is in the hundreds place',
      explanation: 'In 3,456, the 4 is in the hundreds place, worth 400!',
      difficulty: 3,
    ),
    NumeracyQuestion(
      id: 'pv_10',
      skillId: 'skill_place_value',
      question: 'What number is 2,000 + 500 + 30 + 6?',
      options: ['2536', '25036', '2563', '20536'],
      correctIndex: 0,
      hint: '2 thousands, 5 hundreds, 3 tens, 6 ones',
      explanation: '2,000 + 500 + 30 + 6 = 2,536!',
      difficulty: 3,
    ),
    NumeracyQuestion(
      id: 'pv_11',
      skillId: 'skill_place_value',
      question: 'Which digit is in the thousands place in 7,892?',
      options: ['2', '8', '9', '7'],
      correctIndex: 3,
      hint: 'The leftmost digit',
      explanation: 'In 7,892, the 7 is in the thousands place (worth 7,000)!',
      difficulty: 3,
    ),
    NumeracyQuestion(
      id: 'pv_12',
      skillId: 'skill_place_value',
      question: 'Round 4,567 to the nearest thousand.',
      options: ['4,000', '4,500', '5,000', '4,600'],
      correctIndex: 2,
      hint: 'Look at the hundreds digit (5). Is it 5 or more?',
      explanation:
          '4,567 rounds to 5,000. The hundreds digit (5) means round up!',
      difficulty: 3,
    ),
  ];

  static List<NumeracyQuestion> getByDifficulty(int level) {
    return questions.where((q) => q.difficulty <= level).toList();
  }
}

/// Question bank for Math Facts zone - quick recall of number facts
class MathFactsQuestions {
  static const List<NumeracyQuestion> questions = [
    // Level 1 - Addition Facts within 10
    NumeracyQuestion(
      id: 'mf_add_1',
      skillId: 'skill_addition',
      question: '1 + 1 = ?',
      options: ['1', '2', '3', '11'],
      correctIndex: 1,
      hint: 'The simplest fact!',
      explanation: '1 + 1 = 2. A fundamental math fact!',
      difficulty: 1,
    ),
    NumeracyQuestion(
      id: 'mf_add_2',
      skillId: 'skill_addition',
      question: '2 + 2 = ?',
      options: ['2', '3', '4', '5'],
      correctIndex: 2,
      hint: 'Double 2!',
      explanation: '2 + 2 = 4. This is a doubles fact!',
      difficulty: 1,
    ),
    NumeracyQuestion(
      id: 'mf_add_3',
      skillId: 'skill_addition',
      question: '3 + 3 = ?',
      options: ['5', '6', '7', '9'],
      correctIndex: 1,
      hint: 'Double 3!',
      explanation: '3 + 3 = 6. Doubles are easy to remember!',
      difficulty: 1,
    ),
    NumeracyQuestion(
      id: 'mf_add_4',
      skillId: 'skill_addition',
      question: '4 + 4 = ?',
      options: ['6', '7', '8', '9'],
      correctIndex: 2,
      hint: 'Double 4!',
      explanation: '4 + 4 = 8. Another doubles fact!',
      difficulty: 1,
    ),
    NumeracyQuestion(
      id: 'mf_add_5',
      skillId: 'skill_addition',
      question: '5 + 5 = ?',
      options: ['8', '9', '10', '11'],
      correctIndex: 2,
      hint: 'Double 5!',
      explanation: '5 + 5 = 10. This makes a perfect 10!',
      difficulty: 1,
    ),
    NumeracyQuestion(
      id: 'mf_add_6',
      skillId: 'skill_addition',
      question: '6 + 1 = ?',
      options: ['5', '6', '7', '8'],
      correctIndex: 2,
      hint: 'Add one more to 6',
      explanation: '6 + 1 = 7. Adding 1 gives the next number!',
      difficulty: 1,
    ),
    NumeracyQuestion(
      id: 'mf_add_7',
      skillId: 'skill_addition',
      question: '7 + 2 = ?',
      options: ['8', '9', '10', '11'],
      correctIndex: 1,
      hint: '7, 8, 9!',
      explanation: '7 + 2 = 9. Count on from 7!',
      difficulty: 1,
    ),
    NumeracyQuestion(
      id: 'mf_add_8',
      skillId: 'skill_addition',
      question: '3 + 4 = ?',
      options: ['5', '6', '7', '8'],
      correctIndex: 2,
      hint: 'Between 3 + 3 and 4 + 4',
      explanation: '3 + 4 = 7. Near doubles help!',
      difficulty: 1,
    ),

    // Level 2 - Addition facts to 20
    NumeracyQuestion(
      id: 'mf_add_9',
      skillId: 'skill_addition',
      question: '6 + 6 = ?',
      options: ['10', '11', '12', '13'],
      correctIndex: 2,
      hint: 'Double 6!',
      explanation: '6 + 6 = 12. Important doubles fact!',
      difficulty: 2,
    ),
    NumeracyQuestion(
      id: 'mf_add_10',
      skillId: 'skill_addition',
      question: '7 + 7 = ?',
      options: ['12', '13', '14', '15'],
      correctIndex: 2,
      hint: 'Double 7!',
      explanation: '7 + 7 = 14. Lucky doubles!',
      difficulty: 2,
    ),
    NumeracyQuestion(
      id: 'mf_add_11',
      skillId: 'skill_addition',
      question: '8 + 8 = ?',
      options: ['14', '15', '16', '17'],
      correctIndex: 2,
      hint: 'Double 8!',
      explanation: '8 + 8 = 16. Great eights!',
      difficulty: 2,
    ),
    NumeracyQuestion(
      id: 'mf_add_12',
      skillId: 'skill_addition',
      question: '9 + 9 = ?',
      options: ['16', '17', '18', '19'],
      correctIndex: 2,
      hint: 'Double 9!',
      explanation: '9 + 9 = 18. The largest single-digit double!',
      difficulty: 2,
    ),
    NumeracyQuestion(
      id: 'mf_add_13',
      skillId: 'skill_addition',
      question: '8 + 5 = ?',
      options: ['11', '12', '13', '14'],
      correctIndex: 2,
      hint: '8 + 2 = 10, then 3 more',
      explanation: '8 + 5 = 13. Make a 10 first!',
      difficulty: 2,
    ),
    NumeracyQuestion(
      id: 'mf_add_14',
      skillId: 'skill_addition',
      question: '7 + 6 = ?',
      options: ['11', '12', '13', '14'],
      correctIndex: 2,
      hint: 'Near 7 + 7',
      explanation: '7 + 6 = 13. One less than 7 + 7!',
      difficulty: 2,
    ),

    // Level 2 - Subtraction facts within 10
    NumeracyQuestion(
      id: 'mf_sub_1',
      skillId: 'skill_subtraction',
      question: '5 - 3 = ?',
      options: ['1', '2', '3', '4'],
      correctIndex: 1,
      hint: '3 + ? = 5',
      explanation: '5 - 3 = 2. Count back or think addition!',
      difficulty: 2,
    ),
    NumeracyQuestion(
      id: 'mf_sub_2',
      skillId: 'skill_subtraction',
      question: '8 - 4 = ?',
      options: ['3', '4', '5', '6'],
      correctIndex: 1,
      hint: 'Half of 8',
      explanation: '8 - 4 = 4. Four and four make eight!',
      difficulty: 2,
    ),
    NumeracyQuestion(
      id: 'mf_sub_3',
      skillId: 'skill_subtraction',
      question: '10 - 6 = ?',
      options: ['3', '4', '5', '6'],
      correctIndex: 1,
      hint: '6 + ? = 10',
      explanation: '10 - 6 = 4. Think: 6 + 4 = 10!',
      difficulty: 2,
    ),
    NumeracyQuestion(
      id: 'mf_sub_4',
      skillId: 'skill_subtraction',
      question: '9 - 3 = ?',
      options: ['5', '6', '7', '8'],
      correctIndex: 1,
      hint: '3 + 6 = 9',
      explanation: '9 - 3 = 6. Use your addition facts!',
      difficulty: 2,
    ),

    // Level 3 - Multiplication facts 2s, 5s, 10s
    NumeracyQuestion(
      id: 'mf_mult_1',
      skillId: 'skill_multiplication',
      question: '2 × 4 = ?',
      options: ['6', '7', '8', '9'],
      correctIndex: 2,
      hint: 'Double 4!',
      explanation: '2 × 4 = 8. Multiplying by 2 is doubling!',
      difficulty: 3,
    ),
    NumeracyQuestion(
      id: 'mf_mult_2',
      skillId: 'skill_multiplication',
      question: '5 × 3 = ?',
      options: ['12', '13', '14', '15'],
      correctIndex: 3,
      hint: 'Count by 5s: 5, 10, 15',
      explanation: '5 × 3 = 15. Three fives!',
      difficulty: 3,
    ),
    NumeracyQuestion(
      id: 'mf_mult_3',
      skillId: 'skill_multiplication',
      question: '10 × 6 = ?',
      options: ['50', '60', '70', '80'],
      correctIndex: 1,
      hint: 'Just add a zero!',
      explanation: '10 × 6 = 60. Multiplying by 10 is easy!',
      difficulty: 3,
    ),
    NumeracyQuestion(
      id: 'mf_mult_4',
      skillId: 'skill_multiplication',
      question: '2 × 7 = ?',
      options: ['12', '13', '14', '15'],
      correctIndex: 2,
      hint: 'Double 7!',
      explanation: '2 × 7 = 14. Two sevens are fourteen!',
      difficulty: 3,
    ),
    NumeracyQuestion(
      id: 'mf_mult_5',
      skillId: 'skill_multiplication',
      question: '5 × 6 = ?',
      options: ['25', '28', '30', '35'],
      correctIndex: 2,
      hint: 'Half of 10 × 6',
      explanation: '5 × 6 = 30. Six fives equal thirty!',
      difficulty: 3,
    ),
    NumeracyQuestion(
      id: 'mf_mult_6',
      skillId: 'skill_multiplication',
      question: '10 × 9 = ?',
      options: ['80', '85', '90', '95'],
      correctIndex: 2,
      hint: 'Add a zero to 9!',
      explanation: '10 × 9 = 90. Nine tens!',
      difficulty: 3,
    ),
    NumeracyQuestion(
      id: 'mf_mult_7',
      skillId: 'skill_multiplication',
      question: '3 × 3 = ?',
      options: ['6', '7', '8', '9'],
      correctIndex: 3,
      hint: 'Three threes!',
      explanation: '3 × 3 = 9. A square number!',
      difficulty: 3,
    ),
    NumeracyQuestion(
      id: 'mf_mult_8',
      skillId: 'skill_multiplication',
      question: '4 × 4 = ?',
      options: ['12', '14', '16', '18'],
      correctIndex: 2,
      hint: 'Four fours!',
      explanation: '4 × 4 = 16. Another square number!',
      difficulty: 3,
    ),

    // Number bonds to 10
    NumeracyQuestion(
      id: 'mf_bond_1',
      skillId: 'skill_addition',
      question: 'What makes 10 with 3?',
      options: ['6', '7', '8', '9'],
      correctIndex: 1,
      hint: '3 + ? = 10',
      explanation: '3 + 7 = 10. An important number bond!',
      difficulty: 2,
    ),
    NumeracyQuestion(
      id: 'mf_bond_2',
      skillId: 'skill_addition',
      question: 'What makes 10 with 6?',
      options: ['3', '4', '5', '6'],
      correctIndex: 1,
      hint: '6 + ? = 10',
      explanation: '6 + 4 = 10. Memorize these bonds!',
      difficulty: 2,
    ),
    NumeracyQuestion(
      id: 'mf_bond_3',
      skillId: 'skill_addition',
      question: 'What makes 10 with 8?',
      options: ['1', '2', '3', '4'],
      correctIndex: 1,
      hint: '8 + ? = 10',
      explanation: '8 + 2 = 10. Number bonds are powerful!',
      difficulty: 2,
    ),
    NumeracyQuestion(
      id: 'mf_bond_4',
      skillId: 'skill_addition',
      question: 'What makes 10 with 9?',
      options: ['0', '1', '2', '3'],
      correctIndex: 1,
      hint: '9 + ? = 10',
      explanation: '9 + 1 = 10. Just one more!',
      difficulty: 2,
    ),
  ];

  static List<NumeracyQuestion> getByDifficulty(int level) {
    return questions.where((q) => q.difficulty <= level).toList();
  }
}

/// Question bank for decimals (Gap Fix - Years 4-6)
/// ACARA codes: ACMNA079, ACMNA100, ACMNA127
class DecimalQuestions {
  static const List<NumeracyQuestion> questions = [
    // Level 1 - Decimal notation introduction (Year 4)
    NumeracyQuestion(
      id: 'dec_1',
      skillId: 'skill_decimals',
      question: 'What does the 5 represent in 2.5?',
      options: ['5 ones', '5 tenths', '5 tens', '5 hundredths'],
      correctIndex: 1,
      hint: 'The digit after the decimal point is...',
      explanation: 'In 2.5, the 5 is in the tenths place. 2.5 = 2 ones + 5 tenths',
      difficulty: 2,
    ),
    NumeracyQuestion(
      id: 'dec_2',
      skillId: 'skill_decimals',
      question: '0.3 + 0.4 = ?',
      options: ['0.6', '0.7', '0.8', '0.9'],
      correctIndex: 1,
      hint: '3 tenths + 4 tenths = ?',
      explanation: '0.3 + 0.4 = 0.7 (3 tenths + 4 tenths = 7 tenths)',
      difficulty: 2,
    ),
    NumeracyQuestion(
      id: 'dec_3',
      skillId: 'skill_decimals',
      question: 'Which decimal is larger: 1.2 or 1.7?',
      options: ['1.2', '1.7', 'They are equal', 'Cannot compare'],
      correctIndex: 1,
      hint: 'Compare the tenths place',
      explanation: '1.7 > 1.2 because 7 tenths > 2 tenths',
      difficulty: 2,
    ),
    NumeracyQuestion(
      id: 'dec_4',
      skillId: 'skill_decimals',
      question: '3.0 - 1.5 = ?',
      options: ['1.4', '1.5', '1.6', '1.7'],
      correctIndex: 1,
      hint: 'Think: 3 - 1.5 = ?',
      explanation: '3.0 - 1.5 = 1.5. Breaking down: 3 - 1 = 2, then 2 - 0.5 = 1.5',
      difficulty: 2,
    ),

    // Level 2 - Hundredths and comparison (Year 5)
    NumeracyQuestion(
      id: 'dec_5',
      skillId: 'skill_decimals',
      question: 'What does 0.25 represent?',
      options: ['2 hundredths, 5 tenths', '2 tenths, 5 hundredths', '25 hundredths', '25 tenths'],
      correctIndex: 2,
      hint: 'Count the decimal places',
      explanation: '0.25 = 25 hundredths = 2 tenths and 5 hundredths',
      difficulty: 3,
    ),
    NumeracyQuestion(
      id: 'dec_6',
      skillId: 'skill_decimals',
      question: 'Order from smallest to largest: 0.4, 0.04, 0.14',
      options: ['0.04, 0.14, 0.4', '0.4, 0.14, 0.04', '0.14, 0.04, 0.4', '0.04, 0.4, 0.14'],
      correctIndex: 0,
      hint: 'Convert to hundredths: 0.40, 0.04, 0.14',
      explanation: '0.04 < 0.14 < 0.4 (remember: compare digit by digit from left)',
      difficulty: 3,
    ),
    NumeracyQuestion(
      id: 'dec_7',
      skillId: 'skill_decimals',
      question: '1.5 + 2.3 = ?',
      options: ['3.7', '3.8', '3.9', '4.0'],
      correctIndex: 1,
      hint: '1 + 2 = 3, then 0.5 + 0.3 = ?',
      explanation: '1.5 + 2.3 = 3.8 (0.5 + 0.3 = 0.8, so total is 3.8)',
      difficulty: 3,
    ),
    NumeracyQuestion(
      id: 'dec_8',
      skillId: 'skill_decimals',
      question: 'What is 0.1 × 3?',
      options: ['0.2', '0.3', '0.4', '0.5'],
      correctIndex: 1,
      hint: '0.1 + 0.1 + 0.1 = ?',
      explanation: '0.1 × 3 = 0.3 (three tenths)',
      difficulty: 3,
    ),

    // Level 3 - Decimal operations and applications (Year 6)
    NumeracyQuestion(
      id: 'dec_9',
      skillId: 'skill_decimals',
      question: 'A drink costs \$2.45. You pay \$5. How much change?',
      options: ['\$2.45', '\$2.50', '\$2.55', '\$3.55'],
      correctIndex: 2,
      hint: '\$5.00 - \$2.45 = ?',
      explanation: '\$5.00 - \$2.45 = \$2.55 (real-world money application)',
      difficulty: 4,
    ),
    NumeracyQuestion(
      id: 'dec_10',
      skillId: 'skill_decimals',
      question: '3.25 + 1.75 + 2.5 = ?',
      options: ['6.5', '7.0', '7.5', '8.0'],
      correctIndex: 2,
      hint: 'Add the ones, then add the decimals',
      explanation: '3.25 + 1.75 + 2.5 = 7.5 (multi-step decimal addition)',
      difficulty: 4,
    ),
    NumeracyQuestion(
      id: 'dec_11',
      skillId: 'skill_decimals',
      question: 'If 5 apples cost \$3.50, what does 1 apple cost?',
      options: ['\$0.60', '\$0.70', '\$0.80', '\$0.90'],
      correctIndex: 1,
      hint: '\$3.50 ÷ 5 = ?',
      explanation: '\$3.50 ÷ 5 = \$0.70 per apple (division application)',
      difficulty: 4,
    ),
    NumeracyQuestion(
      id: 'dec_12',
      skillId: 'skill_decimals',
      question: '6.4 - 2.8 = ?',
      options: ['3.4', '3.5', '3.6', '3.7'],
      correctIndex: 2,
      hint: 'Rewrite as 6.4 - 2.8. Think: 6.4 - 3 + 0.2',
      explanation: '6.4 - 2.8 = 3.6 (subtraction with regrouping)',
      difficulty: 4,
    ),
    NumeracyQuestion(
      id: 'dec_13',
      skillId: 'skill_decimals',
      question: 'Which is the best estimate: 7.8 + 2.1?',
      options: ['8', '9', '10', '11'],
      correctIndex: 1,
      hint: 'Round to nearest whole number',
      explanation: '7.8 ≈ 8, 2.1 ≈ 2, so 8 + 2 = 10... but 7.8 + 2.1 is closer to 10',
      difficulty: 4,
    ),
  ];

  static List<NumeracyQuestion> getByDifficulty(int level) {
    return questions.where((q) => q.difficulty <= level).toList();
  }
}

/// Question bank for data interpretation and statistics (Gap Fix - Years 3-6)
/// ACARA codes: ACMSP069, ACMSP088, ACMSP111, ACMSP147
class DataInterpretationQuestions {
  static const List<NumeracyQuestion> questions = [
    // Level 1 - Simple data reading (Year 3)
    NumeracyQuestion(
      id: 'data_1',
      skillId: 'skill_data_interpretation',
      question: 'How many students like pizza? (From: Pizza 5, Burgers 3, Salad 2)',
      options: ['2', '3', '5', '10'],
      correctIndex: 2,
      hint: 'Find "Pizza" in the list',
      explanation: 'Pizza is liked by 5 students',
      difficulty: 2,
    ),
    NumeracyQuestion(
      id: 'data_2',
      skillId: 'skill_data_interpretation',
      question: 'Which has more votes? (Red 7, Blue 4, Green 5)',
      options: ['Red', 'Blue', 'Green', 'Red and Blue'],
      correctIndex: 0,
      hint: '7 is greater than 4 and 5',
      explanation: 'Red has 7 votes, which is more than Blue (4) and Green (5)',
      difficulty: 2,
    ),
    NumeracyQuestion(
      id: 'data_3',
      skillId: 'skill_data_interpretation',
      question: 'What is the difference between the most and least popular? (Mon 8, Tue 5, Wed 3)',
      options: ['3', '4', '5', '8'],
      correctIndex: 2,
      hint: '8 - 3 = ?',
      explanation: 'Monday (8) - Wednesday (3) = 5 (range)',
      difficulty: 2,
    ),

    // Level 2 - Graph reading and analysis (Year 4)
    NumeracyQuestion(
      id: 'data_4',
      skillId: 'skill_data_interpretation',
      question: 'In a bar graph, the x-axis shows months and y-axis shows temperature. Which is the hottest month?',
      options: ['The month with tallest bar', 'The month with shortest bar', 'The first month', 'The last month'],
      correctIndex: 0,
      hint: 'Higher bars = higher values',
      explanation: 'In a bar graph, the tallest bar represents the highest value',
      difficulty: 3,
    ),
    NumeracyQuestion(
      id: 'data_5',
      skillId: 'skill_data_interpretation',
      question: 'Class scores: 80, 85, 90, 85, 80. What is the mode?',
      options: ['80', '85', '90', '87'],
      correctIndex: 1,
      hint: 'Mode is the number that appears most often',
      explanation: '85 appears twice, while 80 and 90 appear once each. Mode = 85',
      difficulty: 3,
    ),
    NumeracyQuestion(
      id: 'data_6',
      skillId: 'skill_data_interpretation',
      question: 'Test results: 70, 75, 80, 85, 90. What is the median?',
      options: ['70', '75', '80', '85'],
      correctIndex: 2,
      hint: 'Median is the middle value when ordered',
      explanation: 'Ordered: 70, 75, 80, 85, 90. Middle value (median) = 80',
      difficulty: 3,
    ),

    // Level 3 - Data analysis and estimation (Year 5-6)
    NumeracyQuestion(
      id: 'data_7',
      skillId: 'skill_data_interpretation',
      question: 'Average test score: (80 + 85 + 75 + 90) ÷ 4 = ?',
      options: ['80', '82', '82.5', '85'],
      correctIndex: 2,
      hint: 'Sum all and divide by count',
      explanation: '(80 + 85 + 75 + 90) ÷ 4 = 330 ÷ 4 = 82.5 (mean)',
      difficulty: 4,
    ),
    NumeracyQuestion(
      id: 'data_8',
      skillId: 'skill_data_interpretation',
      question: 'If a survey shows 60% prefer dogs and 40% prefer cats, how many prefer dogs out of 100 people?',
      options: ['40', '50', '60', '70'],
      correctIndex: 2,
      hint: '60% of 100 = ?',
      explanation: '60% of 100 = (60/100) × 100 = 60 people',
      difficulty: 4,
    ),
    NumeracyQuestion(
      id: 'data_9',
      skillId: 'skill_data_interpretation',
      question: 'A shop sells apples (25%), oranges (35%), bananas (40%). Which is most popular?',
      options: ['Apples', 'Oranges', 'Bananas', 'Apples and Oranges'],
      correctIndex: 2,
      hint: '40% is larger than 35% and 25%',
      explanation: 'Bananas at 40% is the highest percentage',
      difficulty: 4,
    ),
    NumeracyQuestion(
      id: 'data_10',
      skillId: 'skill_data_interpretation',
      question: 'Student heights: 140cm, 145cm, 142cm, 148cm, 141cm. Which measures the spread of data?',
      options: ['Mode', 'Median', 'Range', 'Mean'],
      correctIndex: 2,
      hint: 'Range = highest - lowest',
      explanation: 'Range = 148 - 140 = 8cm (shows how spread out the data is)',
      difficulty: 4,
    ),
  ];

  static List<NumeracyQuestion> getByDifficulty(int level) {
    return questions.where((q) => q.difficulty <= level).toList();
  }
}

/// Advanced geometry questions (Gap Fix - Years 4-6)
/// ACARA codes: ACMMG062, ACMMG087, ACMMG112, ACMMG143
class AdvancedGeometryQuestions {
  static const List<NumeracyQuestion> questions = [
    // Level 1 - 3D shapes identification (Year 4)
    NumeracyQuestion(
      id: 'geo3d_1',
      skillId: 'skill_geometry_3d',
      question: 'What 3D shape is a soccer ball?',
      options: ['Cube', 'Sphere', 'Cylinder', 'Pyramid'],
      correctIndex: 1,
      hint: 'It rolls in all directions',
      explanation: 'A soccer ball is a sphere (or nearly spherical)',
      difficulty: 2,
    ),
    NumeracyQuestion(
      id: 'geo3d_2',
      skillId: 'skill_geometry_3d',
      question: 'How many faces does a cube have?',
      options: ['4', '6', '8', '12'],
      correctIndex: 1,
      hint: 'Think of a die',
      explanation: 'A cube has 6 square faces',
      difficulty: 2,
    ),
    NumeracyQuestion(
      id: 'geo3d_3',
      skillId: 'skill_geometry_3d',
      question: 'What 3D shape is a can of soup?',
      options: ['Cone', 'Cylinder', 'Prism', 'Sphere'],
      correctIndex: 1,
      hint: 'It has circular top and bottom',
      explanation: 'A soup can is a cylinder',
      difficulty: 2,
    ),
    NumeracyQuestion(
      id: 'geo3d_4',
      skillId: 'skill_geometry_3d',
      question: 'A pyramid has a square base. How many vertices does it have?',
      options: ['4', '5', '8', '9'],
      correctIndex: 1,
      hint: '4 at base + 1 at top',
      explanation: 'A square pyramid has 5 vertices (4 at base + 1 apex)',
      difficulty: 3,
    ),

    // Level 2 - 3D properties and transformations (Year 5)
    NumeracyQuestion(
      id: 'geo3d_5',
      skillId: 'skill_geometry_3d',
      question: 'If you flip a shape vertically, which transformation is this?',
      options: ['Rotation', 'Translation', 'Reflection', 'Scaling'],
      correctIndex: 2,
      hint: 'Mirror image',
      explanation: 'A vertical flip is a reflection (mirror image)',
      difficulty: 3,
    ),
    NumeracyQuestion(
      id: 'geo3d_6',
      skillId: 'skill_geometry_3d',
      question: 'What is the volume of a rectangular prism: length 5cm, width 3cm, height 2cm?',
      options: ['10', '15', '30', '60'],
      correctIndex: 2,
      hint: 'Volume = length × width × height',
      explanation: '5 × 3 × 2 = 30 cubic cm',
      difficulty: 4,
    ),
    NumeracyQuestion(
      id: 'geo3d_7',
      skillId: 'skill_geometry_3d',
      question: 'How many edges does a triangular prism have?',
      options: ['6', '8', '9', '12'],
      correctIndex: 2,
      hint: '3 on top triangle, 3 on bottom, 3 connecting',
      explanation: 'A triangular prism has 9 edges',
      difficulty: 4,
    ),
    NumeracyQuestion(
      id: 'geo3d_8',
      skillId: 'skill_geometry_3d',
      question: 'If you rotate a shape 90° clockwise, by how many degrees should you rotate to return to original?',
      options: ['90°', '180°', '270°', '360°'],
      correctIndex: 2,
      hint: '3 × 90° = ?',
      explanation: '3 more 90° rotations (270° total) returns to original position',
      difficulty: 4,
    ),
  ];

  static List<NumeracyQuestion> getByDifficulty(int level) {
    return questions.where((q) => q.difficulty <= level).toList();
  }
}

/// Higher-order thinking numeracy questions (Evaluate/Create levels)
/// Addresses Bloom's taxonomy gap: Evaluate (5.0) and Create (6.0)
class HigherOrderThinkingNumeracyQuestions {
  static const List<NumeracyQuestion> questions = [
    // Evaluate level (Level 5)
    NumeracyQuestion(
      id: 'hot_eval_1',
      skillId: 'skill_problem_solving',
      question: 'Two solutions: A) 5 + 3 = 8, B) 5 + 3 = 9. Which is correct and why?',
      options: ['A is correct: 5 + 3 = 8', 'B is correct: 5 + 3 = 9', 'Both could be correct', 'Neither is correct'],
      correctIndex: 0,
      hint: 'Count on your fingers',
      explanation: 'A is correct. 5 + 3 = 8. We can verify by counting: 5, 6, 7, 8',
      difficulty: 4,
    ),
    NumeracyQuestion(
      id: 'hot_eval_2',
      skillId: 'skill_problem_solving',
      question: 'A shop has 2 methods to calculate discount. Method 1: Take \$5 off. Method 2: Take 20% off a \$25 item. Which saves more?',
      options: ['Method 1 saves \$5', 'Method 2 saves \$5', 'Methods save equally', 'Cannot determine'],
      correctIndex: 1,
      hint: '20% of \$25 = ?',
      explanation: 'Method 1: \$5 off. Method 2: 20% of \$25 = \$5 off. Both save equally!',
      difficulty: 5,
    ),
    NumeracyQuestion(
      id: 'hot_eval_3',
      skillId: 'skill_problem_solving',
      question: 'Which number sentence best checks if 24 ÷ 3 = 8?',
      options: ['24 - 3 = 21', '24 ÷ 8 = 3', '3 + 3 + 3 = 9', '8 + 8 + 8 = 24'],
      correctIndex: 1,
      hint: 'Division and multiplication are inverse operations',
      explanation: '24 ÷ 8 = 3 checks it, OR 8 × 3 = 24 checks it. Both confirm the answer.',
      difficulty: 5,
    ),
    NumeracyQuestion(
      id: 'hot_eval_4',
      skillId: 'skill_problem_solving',
      question: 'Average of 5 scores is 80. One score was 100. Without calculating, is the average of remaining 4 scores above or below 80?',
      options: ['Definitely above 80', 'Definitely below 80', 'Could be either', 'Exactly 80'],
      correctIndex: 1,
      hint: 'Removing a score above the average lowers the average',
      explanation: 'Since 100 > 80, removing it lowers the average. Remaining average < 80',
      difficulty: 5,
    ),

    // Create level (Level 6)
    NumeracyQuestion(
      id: 'hot_create_1',
      skillId: 'skill_problem_solving',
      question: 'Create a number story for 12 ÷ 3 = 4',
      options: ['12 apples shared among 3 friends, 4 each', 'I have 3 apples and 12 oranges', 'The total is 12 and 3', '3 + 4 = 12'],
      correctIndex: 0,
      hint: 'Division is splitting/sharing',
      explanation: '12 ÷ 3 = 4 means 12 items split 3 ways gives 4 items per way',
      difficulty: 5,
    ),
    NumeracyQuestion(
      id: 'hot_create_2',
      skillId: 'skill_problem_solving',
      question: 'If a store profits \$50 per item. How many items must sell to reach \$500 profit? Create and solve.',
      options: ['10 items', '15 items', 'Cannot determine', '50 items'],
      correctIndex: 0,
      hint: '\$500 ÷ \$50 = ?',
      explanation: '\$500 ÷ \$50 per item = 10 items. Problem: Profit × Quantity = Total Profit',
      difficulty: 5,
    ),
    NumeracyQuestion(
      id: 'hot_create_3',
      skillId: 'skill_problem_solving',
      question: 'Design a fair game where you roll a die and want to make it more likely to win. How would you change the rules?',
      options: ['Award points for rolling 1-4', 'Award points for rolling 6 only', 'Award points for rolling 1, 2, or 6', 'Award same points for all outcomes'],
      correctIndex: 0,
      hint: 'Higher probability = more favorable outcomes',
      explanation: 'Rolling 1-4 gives 4/6 chance of winning vs 1 or 2 outcomes with 1/6 or 2/6 chance',
      difficulty: 6,
    ),
    NumeracyQuestion(
      id: 'hot_create_4',
      skillId: 'skill_problem_solving',
      question: 'Invent a discount system where 3 items give better value than 1 item, but worse value than buying 4 items.',
      options: ['Price per item: 1=\$10, 3=\$28, 4=\$36', 'Price per item: 1=\$10, 3=\$32, 4=\$36', 'Price per item: 1=\$10, 3=\$24, 4=\$36', 'Not possible to design'],
      correctIndex: 0,
      hint: 'Compare price per item: 1=\$10/item, 3=\$9.33/item, 4=\$9/item means 3 is middle value',
      explanation: 'Option A: 1=\$10/item, 3=\$9.33/item, 4=\$9/item. 3 gives better value than 1, worse than 4!',
      difficulty: 6,
    ),
    // Year 5-7: Fractions and percentages
    NumeracyQuestion(
      id: 'hot_frac_1',
      skillId: 'skill_problem_solving',
      question: '1/3 + 1/4 = ?',
      options: ['2/7', '7/12', '5/12', '2/12'],
      correctIndex: 1,
      hint: 'Find a common denominator: 12. Then 4/12 + 3/12 = ?',
      explanation: '1/3 = 4/12, 1/4 = 3/12. So 4/12 + 3/12 = 7/12!',
      difficulty: 4,
    ),
    NumeracyQuestion(
      id: 'hot_frac_2',
      skillId: 'skill_problem_solving',
      question: 'What is 3/5 of 40?',
      options: ['20', '24', '30', '32'],
      correctIndex: 1,
      hint: 'Find 1/5 of 40 first, then multiply by 3.',
      explanation: '1/5 of 40 = 8. Then 8 × 3 = 24. So 3/5 of 40 = 24!',
      difficulty: 4,
    ),
    NumeracyQuestion(
      id: 'hot_pct_1',
      skillId: 'skill_problem_solving',
      question: 'A pair of shoes costs \$80. They go on sale at 35% off. What is the sale price?',
      options: ['\$28', '\$45', '\$52', '\$72'],
      correctIndex: 2,
      hint: '35% of \$80 = \$28. Sale price = \$80 − \$28.',
      explanation: '35% of \$80 = 0.35 × 80 = \$28. Sale price = \$80 − \$28 = \$52.',
      difficulty: 4,
    ),
    NumeracyQuestion(
      id: 'hot_pct_2',
      skillId: 'skill_problem_solving',
      question: 'A plant was 20 cm tall. It grew to 25 cm. What is the percentage increase?',
      options: ['5%', '20%', '25%', '125%'],
      correctIndex: 2,
      hint: 'Percentage increase = (increase ÷ original) × 100 = (5 ÷ 20) × 100.',
      explanation: 'Increase = 5 cm. Percentage increase = (5 ÷ 20) × 100 = 25%.',
      difficulty: 5,
    ),
    // Year 6-7: Rates and ratio
    NumeracyQuestion(
      id: 'hot_ratio_1',
      skillId: 'skill_problem_solving',
      question: 'A recipe uses 2 cups of flour for every 3 cups of oats. To make a batch using 12 cups of oats, how much flour is needed?',
      options: ['6 cups', '8 cups', '9 cups', '18 cups'],
      correctIndex: 1,
      hint: 'Ratio is 2:3. If oats = 12, flour = 12 × (2/3).',
      explanation: 'Ratio flour:oats = 2:3. For 12 cups oats: 12 × (2/3) = 8 cups flour.',
      difficulty: 4,
    ),
    NumeracyQuestion(
      id: 'hot_ratio_2',
      skillId: 'skill_problem_solving',
      question: 'A car travels 150 km in 2 hours. What is its average speed?',
      options: ['50 km/h', '60 km/h', '75 km/h', '300 km/h'],
      correctIndex: 2,
      hint: 'Speed = distance ÷ time.',
      explanation: 'Speed = 150 km ÷ 2 h = 75 km/h.',
      difficulty: 4,
    ),
    // Year 6-7: Basic algebra
    NumeracyQuestion(
      id: 'hot_alg_1',
      skillId: 'skill_problem_solving',
      question: 'If 4x = 28, what is x?',
      options: ['5', '6', '7', '8'],
      correctIndex: 2,
      hint: 'Divide both sides by 4.',
      explanation: '4x = 28. Divide both sides by 4: x = 28 ÷ 4 = 7.',
      difficulty: 4,
    ),
    NumeracyQuestion(
      id: 'hot_alg_2',
      skillId: 'skill_problem_solving',
      question: 'Solve: 2x + 3 = 13',
      options: ['x = 4', 'x = 5', 'x = 6', 'x = 7'],
      correctIndex: 1,
      hint: 'Subtract 3 from both sides first: 2x = 10.',
      explanation: '2x + 3 = 13. Subtract 3: 2x = 10. Divide by 2: x = 5.',
      difficulty: 5,
    ),
    NumeracyQuestion(
      id: 'hot_alg_3',
      skillId: 'skill_problem_solving',
      question: 'If y = 3x − 2, what is y when x = 4?',
      options: ['8', '9', '10', '12'],
      correctIndex: 2,
      hint: 'Substitute x = 4 into the rule: y = 3(4) − 2.',
      explanation: 'y = 3 × 4 − 2 = 12 − 2 = 10.',
      difficulty: 5,
    ),
    // Year 6-7: Probability
    NumeracyQuestion(
      id: 'hot_prob_1',
      skillId: 'skill_problem_solving',
      question: 'A bag has 3 red, 2 blue and 5 green marbles. What is the probability of picking red?',
      options: ['1/10', '3/10', '5/10', '7/10'],
      correctIndex: 1,
      hint: 'Probability = favourable ÷ total. Total = 3 + 2 + 5.',
      explanation: 'Total = 10. P(red) = 3/10.',
      difficulty: 4,
    ),
    NumeracyQuestion(
      id: 'hot_prob_2',
      skillId: 'skill_problem_solving',
      question: 'If a dice is rolled, what is the probability of NOT getting a 6?',
      options: ['1/6', '5/6', '1/2', '4/6'],
      correctIndex: 1,
      hint: 'P(not 6) = 1 − P(6). P(6) = 1/6.',
      explanation: 'P(not 6) = 1 − 1/6 = 5/6. There are 5 favourable outcomes (1,2,3,4,5) out of 6.',
      difficulty: 4,
    ),
    // Year 7: Negative numbers
    NumeracyQuestion(
      id: 'hot_neg_1',
      skillId: 'skill_problem_solving',
      question: 'The temperature was −5°C. It rose by 12°C. What is the new temperature?',
      options: ['7°C', '−7°C', '17°C', '−17°C'],
      correctIndex: 0,
      hint: '−5 + 12 = ?',
      explanation: '−5 + 12 = 7°C. Moving right on the number line from −5 by 12 steps lands on 7.',
      difficulty: 5,
    ),
    NumeracyQuestion(
      id: 'hot_neg_2',
      skillId: 'skill_problem_solving',
      question: 'Which list is correctly ordered from smallest to largest?',
      options: ['−10, −5, 0, 3, 8', '−5, −10, 0, 3, 8', '0, −5, −10, 3, 8', '8, 3, 0, −5, −10'],
      correctIndex: 0,
      hint: 'On a number line, more negative = smaller.',
      explanation: '−10 < −5 < 0 < 3 < 8. Negative numbers are always less than positive numbers!',
      difficulty: 5,
    ),
  ];

  static List<NumeracyQuestion> getByDifficulty(int level) {
    return questions.where((q) => q.difficulty <= level).toList();
  }
}
