import 'dart:math';
import 'package:brightbound_adventures/features/logic/models/question.dart';

/// Extended static question bank for Puzzle Peaks.
///
/// Covers: analogies, odd-one-out, number sequences, logical deduction,
/// spatial reasoning, and more complex pattern recognition.
///
/// Use [PuzzlePeaksQuestionBank.get] to draw a shuffled subset by skill/difficulty.
class PuzzlePeaksQuestionBank {
  static final Random _random = Random();

  static const List<LogicQuestion> _all = [
    // ── ANALOGIES: difficulty 2 ───────────────────────────────────────────────

    LogicQuestion(
      id: 'bank_ana_001',
      skillId: 'skill_pattern_recognition',
      question: 'Sun is to Day as Moon is to…?',
      options: ['Morning', 'Night', 'Afternoon', 'Season'],
      correctIndex: 1,
      difficulty: 2,
      type: LogicQuestionType.logicPuzzle,
      hint: 'When do we see the Moon in the sky?',
      explanation: 'The Sun is associated with day; the Moon is associated with night.',
    ),
    LogicQuestion(
      id: 'bank_ana_002',
      skillId: 'skill_pattern_recognition',
      question: 'Cat is to Kitten as Dog is to…?',
      options: ['Puppy', 'Cub', 'Foal', 'Joey'],
      correctIndex: 0,
      difficulty: 2,
      type: LogicQuestionType.logicPuzzle,
      hint: 'A young dog has a special name.',
      explanation: 'A young cat is a kitten; a young dog is a puppy.',
    ),
    LogicQuestion(
      id: 'bank_ana_003',
      skillId: 'skill_pattern_recognition',
      question: 'Pencil is to Drawing as Brush is to…?',
      options: ['Music', 'Painting', 'Writing', 'Sculpting'],
      correctIndex: 1,
      difficulty: 2,
      type: LogicQuestionType.logicPuzzle,
      hint: 'What do you create WITH a brush?',
      explanation: 'A pencil is used for drawing; a brush is used for painting.',
    ),
    LogicQuestion(
      id: 'bank_ana_004',
      skillId: 'skill_pattern_recognition',
      question: 'Library is to Books as Museum is to…?',
      options: ['Paintings', 'Food', 'Exhibits (artefacts)', 'Plants'],
      correctIndex: 2,
      difficulty: 2,
      type: LogicQuestionType.logicPuzzle,
      hint: 'A museum is full of items on display.',
      explanation: 'A library holds books; a museum holds exhibits (artefacts, artworks, specimens).',
    ),
    LogicQuestion(
      id: 'bank_ana_005',
      skillId: 'skill_pattern_recognition',
      question: 'Gloves are to Hands as Socks are to…?',
      options: ['Arms', 'Legs', 'Feet', 'Head'],
      correctIndex: 2,
      difficulty: 2,
      type: LogicQuestionType.logicPuzzle,
      hint: 'Gloves cover hands. Socks cover…',
      explanation: 'Gloves are worn on the hands; socks are worn on the feet.',
    ),
    LogicQuestion(
      id: 'bank_ana_006',
      skillId: 'skill_pattern_recognition',
      question: 'Fish is to Water as Bird is to…?',
      options: ['Tree', 'Air (sky)', 'Grass', 'Cage'],
      correctIndex: 1,
      difficulty: 2,
      type: LogicQuestionType.logicPuzzle,
      hint: 'Both creatures live and move in their natural environment.',
      explanation: 'Fish live and move through water; birds live and move through the air (sky).',
    ),
    LogicQuestion(
      id: 'bank_ana_007',
      skillId: 'skill_pattern_recognition',
      question: 'Doctor is to Hospital as Teacher is to…?',
      options: ['Library', 'Office', 'School', 'Playground'],
      correctIndex: 2,
      difficulty: 2,
      type: LogicQuestionType.logicPuzzle,
      hint: 'Where does a teacher do their job?',
      explanation: 'A doctor works in a hospital; a teacher works in a school.',
    ),
    LogicQuestion(
      id: 'bank_ana_008',
      skillId: 'skill_pattern_recognition',
      question: 'Hot is to Cold as Fast is to…?',
      options: ['Quick', 'Slow', 'Hard', 'Loud'],
      correctIndex: 1,
      difficulty: 2,
      type: LogicQuestionType.logicPuzzle,
      hint: 'Hot and cold are opposites. Fast and ___ are opposites.',
      explanation: 'This is an antonym analogy: hot ↔ cold, fast ↔ slow.',
    ),
    LogicQuestion(
      id: 'bank_ana_009',
      skillId: 'skill_pattern_recognition',
      question: 'Caterpillar is to Butterfly as Tadpole is to…?',
      options: ['Fish', 'Newt', 'Frog', 'Salamander'],
      correctIndex: 2,
      difficulty: 2,
      type: LogicQuestionType.logicPuzzle,
      hint: 'Both undergo metamorphosis — transforming into their adult form.',
      explanation: 'A caterpillar transforms into a butterfly; a tadpole transforms into a frog.',
    ),

    // ── ANALOGIES: difficulty 3 ───────────────────────────────────────────────

    LogicQuestion(
      id: 'bank_ana_010',
      skillId: 'skill_pattern_recognition',
      question: 'Composer is to Symphony as Author is to…?',
      options: ['Song', 'Novel', 'Painting', 'Sculpture'],
      correctIndex: 1,
      difficulty: 3,
      type: LogicQuestionType.logicPuzzle,
      hint: 'A composer creates a symphony; an author creates a…',
      explanation: 'A composer writes a symphony (musical work); an author writes a novel (literary work).',
    ),
    LogicQuestion(
      id: 'bank_ana_011',
      skillId: 'skill_pattern_recognition',
      question: 'Astronomer is to Stars as Geologist is to…?',
      options: ['Plants', 'Rocks', 'Animals', 'Weather'],
      correctIndex: 1,
      difficulty: 3,
      type: LogicQuestionType.logicPuzzle,
      hint: 'Scientists are named after what they study.',
      explanation: 'An astronomer studies stars (and space); a geologist studies rocks (and Earth\'s structure).',
    ),
    LogicQuestion(
      id: 'bank_ana_012',
      skillId: 'skill_pattern_recognition',
      question: 'Centimetre is to Metre as Cent is to…?',
      options: ['Nickel', 'Dollar', 'Penny', 'Note'],
      correctIndex: 1,
      difficulty: 3,
      type: LogicQuestionType.logicPuzzle,
      hint: '100 centimetres = 1 metre; 100 cents = 1 ___.',
      explanation: 'Both relationships involve 100 small units making 1 larger unit: 100 cm = 1 m; 100 cents = \$1.',
    ),
    LogicQuestion(
      id: 'bank_ana_013',
      skillId: 'skill_pattern_recognition',
      question: 'Scale is to Fish as Shell is to…?',
      options: ['Bird', 'Turtle', 'Dog', 'Butterfly'],
      correctIndex: 1,
      difficulty: 3,
      type: LogicQuestionType.logicPuzzle,
      hint: 'Both are protective outer coverings for the creature.',
      explanation: 'A scale covers a fish\'s body; a shell protects a turtle\'s body.',
    ),

    // ── ODD ONE OUT: difficulty 1–2 ───────────────────────────────────────────

    LogicQuestion(
      id: 'bank_odd_001',
      skillId: 'skill_critical_thinking',
      question: 'Which does NOT belong?\n🐕 🐈 🐟 🌸',
      options: ['🌸 (flower)', '🐕 (dog)', '🐈 (cat)', '🐟 (fish)'],
      correctIndex: 0,
      difficulty: 1,
      type: LogicQuestionType.multipleChoice,
      hint: 'Three of these are animals.',
      explanation: 'A flower 🌸 is a plant, not an animal. The dog, cat, and fish are all animals.',
    ),
    LogicQuestion(
      id: 'bank_odd_002',
      skillId: 'skill_critical_thinking',
      question: 'Which does NOT belong?\n🍎 🍊 🍋 🥕',
      options: ['🥕 (carrot)', '🍎 (apple)', '🍊 (orange)', '🍋 (lemon)'],
      correctIndex: 0,
      difficulty: 1,
      type: LogicQuestionType.multipleChoice,
      hint: 'Three are fruits; one is a vegetable.',
      explanation: 'A carrot 🥕 is a vegetable. Apple, orange, and lemon are all fruits.',
    ),
    LogicQuestion(
      id: 'bank_odd_003',
      skillId: 'skill_critical_thinking',
      question: 'Which does NOT belong?\n⚽ 🏀 🎾 🎱',
      options: ['🎱 — wrong category? Actually…', '⚽', '🏀', '🎾'],
      correctIndex: 0,
      difficulty: 1,
      type: LogicQuestionType.multipleChoice,
      hint: 'Three are used in team sports played on courts or fields.',
      explanation: 'All four are balls! This one tests careful reading — all belong to sports.',
    ),
    LogicQuestion(
      id: 'bank_odd_004',
      skillId: 'skill_critical_thinking',
      question: 'Which number does NOT belong?\n2, 4, 6, 9, 10',
      options: ['9', '2', '6', '10'],
      correctIndex: 0,
      difficulty: 2,
      type: LogicQuestionType.multipleChoice,
      hint: 'Look for even numbers.',
      explanation: '2, 4, 6, and 10 are all even. 9 is odd, so it doesn\'t belong.',
    ),
    LogicQuestion(
      id: 'bank_odd_005',
      skillId: 'skill_critical_thinking',
      question: 'Which does NOT belong?\nMercury, Venus, Earth, Sun, Mars',
      options: ['Sun', 'Mercury', 'Venus', 'Mars'],
      correctIndex: 0,
      difficulty: 2,
      type: LogicQuestionType.multipleChoice,
      hint: 'The others are all planets that orbit something.',
      explanation: 'Mercury, Venus, Earth, and Mars are planets. The Sun is a star — it is the centre of our solar system.',
    ),
    LogicQuestion(
      id: 'bank_odd_006',
      skillId: 'skill_critical_thinking',
      question: 'Which word does NOT belong?\nHappy, Joyful, Cheerful, Gloomy',
      options: ['Gloomy', 'Happy', 'Joyful', 'Cheerful'],
      correctIndex: 0,
      difficulty: 2,
      type: LogicQuestionType.multipleChoice,
      hint: 'Three words have a positive (happy) feeling.',
      explanation: 'Happy, joyful, and cheerful all mean the same thing (synonyms for happy). Gloomy means sad.',
    ),
    LogicQuestion(
      id: 'bank_odd_007',
      skillId: 'skill_critical_thinking',
      question: 'Which does NOT belong?\nSquare, Circle, Triangle, Cube',
      options: ['Cube', 'Square', 'Circle', 'Triangle'],
      correctIndex: 0,
      difficulty: 2,
      type: LogicQuestionType.multipleChoice,
      hint: 'Three are flat 2D shapes; one is a 3D solid.',
      explanation: 'Square, circle, and triangle are 2D (flat) shapes. A cube is a 3D solid.',
    ),
    LogicQuestion(
      id: 'bank_odd_008',
      skillId: 'skill_critical_thinking',
      question: 'Which does NOT belong?\nFlute, Drum, Guitar, Clarinet',
      options: ['Drum', 'Flute', 'Guitar', 'Clarinet'],
      correctIndex: 0,
      difficulty: 2,
      type: LogicQuestionType.multipleChoice,
      hint: 'Three are wind or string instruments; one is struck.',
      explanation: 'Flute and clarinet are wind instruments; guitar is a string instrument. A drum is a percussion (struck) instrument.',
    ),
    LogicQuestion(
      id: 'bank_odd_009',
      skillId: 'skill_critical_thinking',
      question: 'Which does NOT belong?\nSydney, Melbourne, Brisbane, Wellington',
      options: ['Wellington', 'Sydney', 'Melbourne', 'Brisbane'],
      correctIndex: 0,
      difficulty: 3,
      type: LogicQuestionType.multipleChoice,
      hint: 'One of these cities is NOT in Australia.',
      explanation: 'Sydney, Melbourne, and Brisbane are Australian cities. Wellington is the capital of New Zealand.',
    ),

    // ── NUMBER SEQUENCES: difficulty 2–4 ──────────────────────────────────────

    LogicQuestion(
      id: 'bank_seq_001',
      skillId: 'skill_pattern_recognition',
      question: 'What comes next?\n3, 6, 9, 12, ?',
      options: ['13', '14', '15', '16'],
      correctIndex: 2,
      difficulty: 2,
      type: LogicQuestionType.patternCompletion,
      hint: 'Each number increases by 3.',
      explanation: 'The pattern adds 3 each time: 3, 6, 9, 12, 15. These are the 3-times table!',
    ),
    LogicQuestion(
      id: 'bank_seq_002',
      skillId: 'skill_pattern_recognition',
      question: 'What comes next?\n1, 2, 4, 8, ?',
      options: ['10', '12', '14', '16'],
      correctIndex: 3,
      difficulty: 3,
      type: LogicQuestionType.patternCompletion,
      hint: 'Each number is doubled.',
      explanation: 'The pattern doubles each time: 1×2=2, 2×2=4, 4×2=8, 8×2=16.',
    ),
    LogicQuestion(
      id: 'bank_seq_003',
      skillId: 'skill_pattern_recognition',
      question: 'What comes next?\n100, 90, 80, 70, ?',
      options: ['60', '65', '55', '50'],
      correctIndex: 0,
      difficulty: 2,
      type: LogicQuestionType.patternCompletion,
      hint: 'Each number decreases by 10.',
      explanation: 'The pattern counts down by 10. 70 − 10 = 60.',
    ),
    LogicQuestion(
      id: 'bank_seq_004',
      skillId: 'skill_pattern_recognition',
      question: 'What comes next?\n1, 3, 6, 10, ?',
      options: ['13', '14', '15', '16'],
      correctIndex: 2,
      difficulty: 3,
      type: LogicQuestionType.patternCompletion,
      hint: 'The differences between terms are: 2, 3, 4, 5…',
      explanation: 'The pattern adds increasing amounts: +2, +3, +4, +5. So 10 + 5 = 15. These are triangle numbers!',
    ),
    LogicQuestion(
      id: 'bank_seq_005',
      skillId: 'skill_pattern_recognition',
      question: 'What comes next?\n2, 5, 10, 17, ?',
      options: ['22', '24', '26', '28'],
      correctIndex: 2,
      difficulty: 4,
      type: LogicQuestionType.patternCompletion,
      hint: 'The differences are increasing odd numbers: 3, 5, 7, 9…',
      explanation: '+3, +5, +7, +9 → 17 + 9 = 26.',
    ),
    LogicQuestion(
      id: 'bank_seq_006',
      skillId: 'skill_pattern_recognition',
      question: 'What letter comes next?\nA, C, E, G, ?',
      options: ['H', 'I', 'J', 'K'],
      correctIndex: 1,
      difficulty: 2,
      type: LogicQuestionType.patternCompletion,
      hint: 'Every second letter of the alphabet.',
      explanation: 'A, C, E, G are every other letter (skip B, D, F). The next is I (skip H).',
    ),
    LogicQuestion(
      id: 'bank_seq_007',
      skillId: 'skill_pattern_recognition',
      question: 'What comes next?\nZ, Y, X, W, ?',
      options: ['A', 'U', 'V', 'T'],
      correctIndex: 2,
      difficulty: 2,
      type: LogicQuestionType.patternCompletion,
      hint: 'The alphabet is going backwards.',
      explanation: 'Z, Y, X, W is the alphabet in reverse. The next letter backwards from W is V.',
    ),
    LogicQuestion(
      id: 'bank_seq_008',
      skillId: 'skill_pattern_recognition',
      question: 'What comes next?\n1, 1, 2, 3, 5, 8, ?',
      options: ['10', '11', '13', '15'],
      correctIndex: 2,
      difficulty: 4,
      type: LogicQuestionType.patternCompletion,
      hint: 'Each number is the SUM of the two numbers before it.',
      explanation: 'This is the Fibonacci sequence: 1+1=2, 1+2=3, 2+3=5, 3+5=8, 5+8=13.',
    ),

    // ── LOGICAL DEDUCTION: difficulty 2–4 ─────────────────────────────────────

    LogicQuestion(
      id: 'bank_log_001',
      skillId: 'skill_logical_thinking',
      question: 'All birds have wings. A penguin is a bird. Does a penguin have wings?',
      options: ['Yes', 'No', 'Only sometimes', 'Only adult penguins'],
      correctIndex: 0,
      difficulty: 2,
      type: LogicQuestionType.logicPuzzle,
      hint: 'Apply the first rule: ALL birds have wings.',
      explanation: 'Logic: All birds have wings + penguin is a bird → therefore a penguin has wings. (Even though penguins can\'t fly, they do have wings.)',
    ),
    LogicQuestion(
      id: 'bank_log_002',
      skillId: 'skill_logical_thinking',
      question: 'Maya is taller than Sam. Sam is taller than Lee. Who is the shortest?',
      options: ['Maya', 'Sam', 'Lee', 'They are all the same'],
      correctIndex: 2,
      difficulty: 2,
      type: LogicQuestionType.logicPuzzle,
      hint: 'Order them from tallest to shortest.',
      explanation: 'Maya > Sam > Lee. Lee is at the bottom of the chain, so Lee is the shortest.',
    ),
    LogicQuestion(
      id: 'bank_log_003',
      skillId: 'skill_logical_thinking',
      question: 'If today is Wednesday, what day was it 3 days ago?',
      options: ['Monday', 'Sunday', 'Saturday', 'Tuesday'],
      correctIndex: 1,
      difficulty: 2,
      type: LogicQuestionType.logicPuzzle,
      hint: 'Count back: Wed → Tue → Mon → Sun.',
      explanation: 'Go back 3 days from Wednesday: Tuesday (1), Monday (2), Sunday (3). The answer is Sunday.',
    ),
    LogicQuestion(
      id: 'bank_log_004',
      skillId: 'skill_logical_thinking',
      question: 'There are 5 apples in a bowl. You take 3. How many do YOU have?',
      options: ['2', '3', '5', '1'],
      correctIndex: 1,
      difficulty: 2,
      type: LogicQuestionType.logicPuzzle,
      hint: 'The question asks how many YOU have, not how many are left.',
      explanation: 'You took 3 apples, so you have 3. There are 2 left in the bowl but the question is about you!',
    ),
    LogicQuestion(
      id: 'bank_log_005',
      skillId: 'skill_logical_thinking',
      question: 'Some cats are black. Felix is a cat. Is Felix definitely black?',
      options: ['Yes, definitely', 'No — not necessarily', 'Only at night', 'Yes, all cats are black'],
      correctIndex: 1,
      difficulty: 3,
      type: LogicQuestionType.logicPuzzle,
      hint: '"Some" does not mean "all".',
      explanation: '"Some cats are black" means not all. Felix might be black, or might not be. We cannot conclude Felix is definitely black.',
    ),
    LogicQuestion(
      id: 'bank_log_006',
      skillId: 'skill_logical_thinking',
      question: 'If all squares are rectangles, is a square a rectangle?',
      options: ['Yes', 'No', 'Only if it has equal sides', 'Only sometimes'],
      correctIndex: 0,
      difficulty: 3,
      type: LogicQuestionType.logicPuzzle,
      hint: '"All squares are rectangles" — what does this directly tell us?',
      explanation: 'If the rule says "all squares are rectangles," then we can conclude any square IS a rectangle.',
    ),
    LogicQuestion(
      id: 'bank_log_007',
      skillId: 'skill_logical_thinking',
      question: 'A bag has 3 red marbles and 2 blue marbles. You pick one without looking. Which colour are you MORE LIKELY to pick?',
      options: ['Blue', 'Red', 'Both equally likely', 'Cannot know'],
      correctIndex: 1,
      difficulty: 3,
      type: LogicQuestionType.logicPuzzle,
      hint: 'More marbles of one colour = greater chance of picking that colour.',
      explanation: 'There are 3 red and 2 blue. Red has a 3/5 chance; blue has a 2/5 chance. Red is more likely.',
    ),
    LogicQuestion(
      id: 'bank_log_008',
      skillId: 'skill_logical_thinking',
      question: 'Jordan has more stickers than Alex. Alex has more stickers than Riley. Whose collection is in the MIDDLE (not the most, not the least)?',
      options: ['Jordan', 'Alex', 'Riley', 'Cannot tell'],
      correctIndex: 1,
      difficulty: 3,
      type: LogicQuestionType.logicPuzzle,
      hint: 'Order them: Jordan > Alex > Riley.',
      explanation: 'Jordan has the most, Riley has the least, and Alex is in the middle.',
    ),
    LogicQuestion(
      id: 'bank_log_009',
      skillId: 'skill_logical_thinking',
      question: 'A farmer has chickens and cows. He counts 20 legs and 7 heads. How many chickens does he have?',
      options: ['3', '4', '6', '8'],
      correctIndex: 2,
      difficulty: 4,
      type: LogicQuestionType.logicPuzzle,
      hint: 'Chickens have 2 legs, cows have 4. There are 7 animals total.',
      explanation: 'Let c = chickens, w = cows. c + w = 7 and 2c + 4w = 20. From first: w = 7−c → 2c + 4(7−c) = 20 → −2c = −8 → c = 6.',
    ),
    LogicQuestion(
      id: 'bank_log_010',
      skillId: 'skill_logical_thinking',
      question: 'If it is NOT raining, the footpath is dry. The footpath is wet. Is it raining?',
      options: ['Yes', 'No', 'Maybe', 'Cannot tell'],
      correctIndex: 0,
      difficulty: 4,
      type: LogicQuestionType.logicPuzzle,
      hint: 'Use the contrapositive: if the footpath is NOT dry, it must be raining.',
      explanation: 'Rule: not raining → dry. If the footpath is wet (not dry), the rule is broken — so it must be raining.',
    ),

    // ── SPATIAL REASONING: difficulty 2–4 ────────────────────────────────────

    LogicQuestion(
      id: 'bank_spat_001',
      skillId: 'skill_spatial_reasoning',
      question: 'You are facing North. You turn right. Which direction are you facing?',
      options: ['South', 'West', 'East', 'North-East'],
      correctIndex: 2,
      difficulty: 2,
      type: LogicQuestionType.spatialReasoning,
      hint: 'A right turn from North on a compass is…',
      explanation: 'On a compass, North → turn right (clockwise) → East.',
    ),
    LogicQuestion(
      id: 'bank_spat_002',
      skillId: 'skill_spatial_reasoning',
      question: 'A cube has 6 faces. How many corners (vertices) does a cube have?',
      options: ['6', '8', '10', '12'],
      correctIndex: 1,
      difficulty: 2,
      type: LogicQuestionType.spatialReasoning,
      hint: 'Picture a dice — count the pointy corners.',
      explanation: 'A cube has 8 corners (vertices): the 4 on the top face and 4 on the bottom.',
    ),
    LogicQuestion(
      id: 'bank_spat_003',
      skillId: 'skill_spatial_reasoning',
      question: 'A square piece of paper is folded in half. Then folded in half again. How many equal sections are there when unfolded?',
      options: ['2', '3', '4', '8'],
      correctIndex: 2,
      difficulty: 3,
      type: LogicQuestionType.spatialReasoning,
      hint: 'Each fold doubles the number of sections.',
      explanation: '1st fold → 2 sections. 2nd fold → 4 sections. Unfolding reveals 4 equal squares.',
    ),
    LogicQuestion(
      id: 'bank_spat_004',
      skillId: 'skill_spatial_reasoning',
      question: 'You face East and make a 180° turn. Which direction are you facing?',
      options: ['North', 'South', 'East', 'West'],
      correctIndex: 3,
      difficulty: 3,
      type: LogicQuestionType.spatialReasoning,
      hint: '180° is a half turn — you face the opposite direction.',
      explanation: 'A 180° turn from East faces you West — the opposite direction on the compass.',
    ),
    LogicQuestion(
      id: 'bank_spat_005',
      skillId: 'skill_spatial_reasoning',
      question: 'A rectangular room is 8 metres long and 5 metres wide. What is its perimeter?',
      options: ['13 m', '26 m', '40 m', '20 m'],
      correctIndex: 1,
      difficulty: 3,
      type: LogicQuestionType.spatialReasoning,
      hint: 'Perimeter = add all 4 sides.',
      explanation: 'Perimeter = 2 × (length + width) = 2 × (8+5) = 2 × 13 = 26 metres.',
    ),
    LogicQuestion(
      id: 'bank_spat_006',
      skillId: 'skill_spatial_reasoning',
      question: 'How many faces does a triangular prism have?',
      options: ['3', '4', '5', '6'],
      correctIndex: 2,
      difficulty: 3,
      type: LogicQuestionType.spatialReasoning,
      hint: 'Two triangular ends + three rectangular sides.',
      explanation: 'A triangular prism has 2 triangular faces (ends) + 3 rectangular faces (sides) = 5 faces total.',
    ),

    // ── COMPLEX PATTERNS: difficulty 3–5 ──────────────────────────────────────

    LogicQuestion(
      id: 'bank_cpat_001',
      skillId: 'skill_pattern_recognition',
      question: 'Which rule describes the sequence: 4, 8, 16, 32, 64?',
      options: ['Add 4 each time', 'Multiply by 2 each time', 'Add 8 each time', 'Multiply by 4 each time'],
      correctIndex: 1,
      difficulty: 3,
      type: LogicQuestionType.patternCompletion,
      hint: '4 × 2 = 8, 8 × 2 = 16…',
      explanation: 'Each term is multiplied by 2 (doubling). This is a geometric sequence.',
    ),
    LogicQuestion(
      id: 'bank_cpat_002',
      skillId: 'skill_pattern_recognition',
      question: 'The pattern rule is: start at 50, subtract 7 each time. What is the 4th term?',
      options: ['34', '29', '22', '27'],
      correctIndex: 1,
      difficulty: 3,
      type: LogicQuestionType.patternCompletion,
      hint: '50, 43, 36, ___',
      explanation: '50−7=43, 43−7=36, 36−7=29. The 4th term is 29.',
    ),
    LogicQuestion(
      id: 'bank_cpat_003',
      skillId: 'skill_pattern_recognition',
      question: 'In a grid of shapes: Row 1 has ▲▲▲, Row 2 has ■■■■, Row 3 would have how many ●●● if the pattern is +1 shape each row?',
      options: ['3', '4', '5', '6'],
      correctIndex: 2,
      difficulty: 3,
      type: LogicQuestionType.patternCompletion,
      hint: 'Row 1 = 3, Row 2 = 4, Row 3 = ?',
      explanation: 'Each row adds one more shape: 3, 4, 5. Row 3 has 5 circles.',
    ),
    LogicQuestion(
      id: 'bank_cpat_004',
      skillId: 'skill_pattern_recognition',
      question: 'A rule machine: Input → ×3 → −1 → Output. Input is 5. What is the output?',
      options: ['12', '13', '14', '16'],
      correctIndex: 2,
      difficulty: 4,
      type: LogicQuestionType.patternCompletion,
      hint: 'Apply the two steps in order: first ×3, then −1.',
      explanation: '5 × 3 = 15. 15 − 1 = 14. The output is 14.',
    ),
    LogicQuestion(
      id: 'bank_cpat_005',
      skillId: 'skill_pattern_recognition',
      question: 'What is the missing number?\n? , 14, 28, 42, 56',
      options: ['0', '7', '10', '4'],
      correctIndex: 1,
      difficulty: 4,
      type: LogicQuestionType.patternCompletion,
      hint: 'The pattern adds 14 each time — work backwards.',
      explanation: 'The sequence increases by 14: 14−14=0? No — 14, 28, 42, 56 are the 14-times table. The term before 14 is 7.',
    ),
    LogicQuestion(
      id: 'bank_cpat_006',
      skillId: 'skill_pattern_recognition',
      question: 'In 4 years, Aisha will be twice as old as she is now. How old is she now?',
      options: ['2', '4', '6', '8'],
      correctIndex: 1,
      difficulty: 5,
      type: LogicQuestionType.logicPuzzle,
      hint: 'Let her current age = x. Then x + 4 = 2x.',
      explanation: 'x + 4 = 2x → 4 = x. Aisha is currently 4 years old. In 4 years she will be 8, which is twice 4.',
    ),
  ];

  // ── Public API ──────────────────────────────────────────────────────────────

  /// Returns up to [count] shuffled questions for [skillId] at [difficulty] ±1.
  static List<LogicQuestion> get({
    required String skillId,
    required int difficulty,
    required int count,
  }) {
    const tolerance = 1;
    final filtered = _all.where((q) {
      final skillMatch = skillId.isEmpty ||
          q.skillId == skillId ||
          skillId.contains(q.skillId) ||
          q.skillId.contains(skillId);
      final diffMatch = (q.difficulty - difficulty).abs() <= tolerance;
      return skillMatch && diffMatch;
    }).toList()
      ..shuffle(_random);

    if (filtered.length >= count) return filtered.take(count).toList();

    // Broaden to all questions if not enough at this difficulty/skill
    final broader = _all
        .where((q) =>
            skillId.isEmpty ||
            q.skillId == skillId ||
            q.skillId.contains('skill'))
        .toList()
      ..shuffle(_random);
    return broader.take(count).toList();
  }

  static int get totalCount => _all.length;
}
