import 'package:brightbound_adventures/features/storytelling/models/question.dart';

/// Master bank for Story Springs curation
class StorySpringsSkillQuestions {
  /// Map of skills to their respective question lists
  static final Map<String, List<StoryQuestion>> _skillBanks = {
    'sequencing': _sequencingQuestions,
    'emotions': _emotionQuestions,
    'characters': _characterQuestions,
    'dialogue': _dialogueQuestions,
    'plot': _plotQuestions,
    'description': _descriptionQuestions,
  };

  /// Main entry point to get questions for a skill
  static List<StoryQuestion> getQuestionsForSkill(String skill, int difficulty) {
    final skillLower = skill.toLowerCase();
    
    // Find bank by key or sub-match
    List<StoryQuestion>? bank;
    for (final entry in _skillBanks.entries) {
      if (skillLower.contains(entry.key)) {
        bank = entry.value;
        break;
      }
    }

    if (bank == null || bank.isEmpty) return [];

    // Filter by difficulty (allowing lower difficulty questions as well)
    return bank.where((q) => q.difficulty <= (difficulty + 1)).toList();
  }

  static const List<StoryQuestion> _sequencingQuestions = [
    // Level 1: Basics (3-4 steps)
    StoryQuestion(
      id: 'ss_seq_1',
      skillId: 'skill_story_sequencing',
      question: 'What happens FIRST when getting ready for a day at the beach?',
      options: ['Swim in the ocean', 'Put on sunscreen', 'Build a sandcastle', 'Eat a meat pie'],
      correctIndex: 1,
      hint: 'Sun safety first!',
      difficulty: 1,
      imageEmoji: '🏖️',
    ),
    StoryQuestion(
      id: 'ss_seq_2',
      skillId: 'skill_story_sequencing',
      question: 'How does a Koala joey grow up? What happens SECOND?',
      options: ['It lives in the pouch', 'It starts eating leaves on mom\'s back', 'It finds its own tree', 'It learns to sleep 20 hours'],
      correctIndex: 1,
      hint: 'After the pouch, it hitches a ride!',
      difficulty: 1,
      imageEmoji: '🐨',
    ),
    StoryQuestion(
      id: 'ss_seq_3',
      skillId: 'skill_story_sequencing',
      question: 'Making a Lamington: What happens LAST?',
      options: ['Bake the sponge cake', 'Dip it in chocolate', 'Roll it in coconut', 'Wait for it to cool'],
      correctIndex: 2,
      hint: 'The white fluffy part at the end!',
      difficulty: 1,
      imageEmoji: '🍰',
    ),
    StoryQuestion(
      id: 'ss_seq_4',
      skillId: 'skill_story_sequencing',
      question: 'A storm in the Outback: What happens THIRD?',
      options: ['Clouds get dark', 'Thunder rumbles', 'The rain pours down', 'The sun comes back out'],
      correctIndex: 2,
      hint: 'The actual weather part!',
      difficulty: 1,
      imageEmoji: '⛈️',
    ),
    // Level 2: More complex
    StoryQuestion(
      id: 'ss_seq_5',
      skillId: 'skill_story_sequencing',
      question: 'Watching a game of Cricket: What happens after the bowler throws the ball?',
      options: ['The batsman hits the ball', 'The crowd cheers', 'The game ends', 'Players go to lunch'],
      correctIndex: 0,
      hint: 'Action and reaction!',
      difficulty: 2,
      imageEmoji: '🏏',
    ),
    StoryQuestion(
      id: 'ss_seq_6',
      skillId: 'skill_story_sequencing',
      question: 'Life cycle of a Frog: What happens after the eggs hatch?',
      options: ['Tadpole swims', 'Frog jumps', 'Legs grow', 'Tail disappears'],
      correctIndex: 0,
      hint: 'Think of the little wiggly tail.',
      difficulty: 2,
      imageEmoji: '🐸',
    ),
    StoryQuestion(
      id: 'ss_seq_7',
      skillId: 'skill_story_sequencing',
      question: 'Cause-and-effect: Riley forgot her hat on a scorching 40°C Australian summer day. What is the most DIRECT effect?',
      options: [
        'She immediately gets tired',
        'The sun shines more',
        'She risks sunburn and heat exhaustion',
        'Her friend finds the hat',
      ],
      correctIndex: 2,
      hint: 'Think about sun exposure without protection.',
      difficulty: 3,
      imageEmoji: '🧢',
    ),
    StoryQuestion(
      id: 'ss_seq_8',
      skillId: 'skill_story_sequencing',
      question: 'A story starts: "Now, ten years later, Jade stood at the top of the cliff — but it was that rainy afternoon at age seven that had started it all." What technique is being used?',
      options: [
        'Foreshadowing — hinting at what comes next',
        'Flashback — the narrator looks back at a past event',
        'Cliffhanger — leaving the reader in suspense',
        'Dialogue — a character speaks',
      ],
      correctIndex: 1,
      hint: 'The narrator jumps back in time from the present to the past.',
      difficulty: 4,
      imageEmoji: '⌛',
    ),
    StoryQuestion(
      id: 'ss_seq_9',
      skillId: 'skill_story_sequencing',
      question: 'A book has three parallel storylines happening at the same time: a scientist in Melbourne, a fisherman in Darwin, and a student in Hobart. What is this narrative technique?',
      options: [
        'Linear narrative — events in time order',
        'Circular narrative — ending where it began',
        'Parallel narrative — multiple storylines running at the same time',
        'Retrospective narrative — looking back at the past',
      ],
      correctIndex: 2,
      hint: 'All three stories are happening simultaneously in different locations.',
      difficulty: 5,
      imageEmoji: '🗺️',
    ),
  ];

  static const List<StoryQuestion> _emotionQuestions = [
    StoryQuestion(
      id: 'ss_emo_1',
      skillId: 'skill_emotion_recognition',
      question: 'The Matildas just scored a goal at the World Cup! How does the crowd feel?',
      options: ['Disappointed', 'Ecstatic & Joyful', 'Bored', 'Sleepy'],
      correctIndex: 1,
      hint: 'A huge achievement for Australia!',
      difficulty: 1,
      imageEmoji: '⚽',
    ),
    StoryQuestion(
      id: 'ss_emo_2',
      skillId: 'skill_emotion_recognition',
      question: 'Benny Bear sees a huge huntsman spider in his tent. How does he feel?',
      options: ['Terrified', 'Hungry', 'Relaxed', 'Proud'],
      correctIndex: 0,
      hint: 'Spiders can be very scary!',
      difficulty: 1,
      imageEmoji: '🕷️',
    ),
    StoryQuestion(
      id: 'ss_emo_3',
      skillId: 'skill_emotion_recognition',
      question: 'Little Roo lost his favorite boomerang in the tall grass. How does he feel?',
      options: ['Upset & Sad', 'Excited', 'Funny', 'Brave'],
      correctIndex: 0,
      hint: 'Losing something you love is hard.',
      difficulty: 1,
      imageEmoji: '🪃',
    ),
    StoryQuestion(
      id: 'ss_emo_4',
      skillId: 'skill_emotion_recognition',
      question: 'The surfers are waiting for a wave at Bells Beach, but no waves are coming. How do they feel?',
      options: ['Impatient', 'Scared', 'Cold', 'Surprised'],
      correctIndex: 0,
      hint: 'Waiting a long time for something good...',
      difficulty: 2,
      imageEmoji: '🏄',
    ),
    StoryQuestion(
      id: 'ss_emo_5',
      skillId: 'skill_emotion_recognition',
      question: 'Kylie is trying Vegemite for the FIRST time. She\'s not sure if she\'ll like it. She feels...',
      options: ['Apprehensive/Hesitant', 'Guilty', 'Angry', 'Confident'],
      correctIndex: 0,
      hint: 'A new, strong taste can be worrying!',
      difficulty: 2,
      imageEmoji: '🍞',
    ),
    StoryQuestion(
      id: 'ss_emo_6',
      skillId: 'skill_emotion_recognition',
      question: 'Jasmine wins the school cross-country race but her best friend comes last. Jasmine feels proud AND...',
      options: [
        'Angry at her friend for losing',
        'Only happy without any other feeling',
        'Torn — guilty because she is excited while her friend is disappointed',
        'Bored because winning is easy',
      ],
      correctIndex: 2,
      hint: 'Can you feel two different things at the same time when someone else is hurting?',
      difficulty: 3,
      imageEmoji: '🏃',
    ),
    StoryQuestion(
      id: 'ss_emo_7',
      skillId: 'skill_emotion_recognition',
      question: 'A character says "Yeah, sure, this is totally fine" while his hands shake and he avoids eye contact. He is actually feeling...',
      options: [
        'Perfectly calm and happy',
        'Anxious but concealing it with sarcasm',
        'Excited',
        'Confused',
      ],
      correctIndex: 1,
      hint: 'His words say one thing but his body language reveals another. This is sarcasm masking anxiety.',
      difficulty: 4,
      imageEmoji: '😓',
    ),
    StoryQuestion(
      id: 'ss_emo_8',
      skillId: 'skill_emotion_recognition',
      question: 'To write a character experiencing grief authentically, a skilled author would MOST likely...',
      options: [
        'Simply write "She was very sad"',
        'Describe physical sensations, behaviours, and moments when grief suddenly resurfaces',
        'Move past it quickly so the story keeps going',
        'Only mention it once',
      ],
      correctIndex: 1,
      hint: 'Real grief is complex, physical, and comes in waves at unexpected moments.',
      difficulty: 5,
      imageEmoji: '🌧️',
    ),
  ];

  static const List<StoryQuestion> _characterQuestions = [
    StoryQuestion(
      id: 'ss_char_1',
      skillId: 'skill_character_development',
      question: 'Wally the Wombat always shares his burrow during a bushfire. What trait is this?',
      options: ['Selfless & Kind', 'Greedy', 'Cowardly', 'Noisy'],
      correctIndex: 0,
      hint: 'He is thinking of others.',
      difficulty: 1,
      imageEmoji: '🕳️',
    ),
    StoryQuestion(
      id: 'ss_char_2',
      skillId: 'skill_character_development',
      question: 'Pip the Penguin practices his slide every single day until he master it. Pip is...',
      options: ['Persistent', 'Lazy', 'Mean', 'Silly'],
      correctIndex: 0,
      hint: 'He keeps trying even if it\'s hard.',
      difficulty: 1,
      imageEmoji: '🐧',
    ),
    StoryQuestion(
      id: 'ss_char_3',
      skillId: 'skill_character_development',
      question: 'Which of these would be a "Hero" trait in a story?',
      options: ['Bravery', 'Sneakiness', 'Rudeness', 'Bullying'],
      correctIndex: 0,
      hint: 'Heroes do good things.',
      difficulty: 1,
      imageEmoji: '🦸',
    ),
    StoryQuestion(
      id: 'ss_char_4',
      skillId: 'skill_character_development',
      question: 'Oscar the Echidna breaks his friend\'s toy by accident. He says sorry and offers to fix it. What character trait does this show?',
      options: ['Responsibility', 'Jealousy', 'Impatience', 'Arrogance'],
      correctIndex: 0,
      hint: 'He owns his mistake and tries to make it right.',
      difficulty: 2,
      imageEmoji: '🦔',
    ),
    StoryQuestion(
      id: 'ss_char_5',
      skillId: 'skill_character_development',
      question: 'In a story, a surfer keeps wiping out but never gives up. Her MOTIVATION (reason for continuing) is most likely...',
      options: [
        'She is bored with other activities',
        'She loves surfing and wants to master it',
        'Her parents force her to surf',
        'She has nothing else to do',
      ],
      correctIndex: 1,
      hint: 'What drives someone to keep trying when it\'s hard?',
      difficulty: 2,
      imageEmoji: '🏄',
    ),
    StoryQuestion(
      id: 'ss_char_6',
      skillId: 'skill_character_development',
      question: 'A character is kind to everyone but is terrified of speaking in public. This makes them...',
      options: [
        'A poorly written character',
        'A realistic character with both strengths and flaws',
        'A villain',
        'A static character',
      ],
      correctIndex: 1,
      hint: 'Real people have good qualities AND weaknesses.',
      difficulty: 3,
      imageEmoji: '🎙️',
    ),
    StoryQuestion(
      id: 'ss_char_7',
      skillId: 'skill_character_development',
      question: 'In a story set in the Queensland rainforest, the cautious cassowary never leaves his territory while the adventurous rosella flies everywhere. These two characters are...',
      options: [
        'Foils — their contrasting traits highlight each other',
        'Identical characters',
        'Protagonist and narrator',
        'Both villains',
      ],
      correctIndex: 0,
      hint: 'Their opposite traits bring out each other\'s qualities.',
      difficulty: 4,
      imageEmoji: '🦜',
    ),
    StoryQuestion(
      id: 'ss_char_8',
      skillId: 'skill_character_development',
      question: 'At the start of the story Mia is selfish and rude. By the end she is caring and brave. Mia is a...',
      options: [
        'Static character — she stays the same',
        'Dynamic character — she changes significantly through events',
        'Foil character',
        'Narrator character',
      ],
      correctIndex: 1,
      hint: 'Dynamic characters grow and change; static characters don\'t.',
      difficulty: 4,
      imageEmoji: '🦋',
    ),
  ];

  static const List<StoryQuestion> _dialogueQuestions = [
    StoryQuestion(
      id: 'ss_dia_1',
      skillId: 'skill_dialogue_creation',
      question: 'How would a friendly Platypus greet a friend?',
      options: ['"G\'day mate! Fancy a swim?"', '"Go away!"', '"I am a rock."', '...Silence...'],
      correctIndex: 0,
      hint: 'Think of common Australian greetings.',
      difficulty: 1,
      imageEmoji: '🦆',
    ),
    StoryQuestion(
      id: 'ss_dia_2',
      skillId: 'skill_dialogue_creation',
      question: 'Which sentence needs quotation marks for dialogue?',
      options: ['The bird sang a song.', 'I love the beach said Toby.', 'It was very hot today.', 'She ran fast.'],
      correctIndex: 1,
      hint: 'Dialogue is what someone says.',
      difficulty: 2,
      imageEmoji: '🗣️',
    ),
    StoryQuestion(
      id: 'ss_dia_3',
      skillId: 'skill_dialogue_creation',
      question: 'Choose the best way to show someone is WHISPERING:',
      options: ['"BE QUIET!" he yelled.', '"Someone is coming," she breathed softly.', '"YES!" he shouted.', '"I am here," he said.'],
      correctIndex: 1,
      hint: 'Soft voices use soft words.',
      difficulty: 2,
      imageEmoji: '🤫',
    ),
    StoryQuestion(
      id: 'ss_dia_4',
      skillId: 'skill_dialogue_creation',
      question: 'Which sentence correctly shows anger WITHOUT using the word "angry"?',
      options: [
        '"I am very angry," said Leo.',
        '"Fine. Whatever," Leo muttered, turning away without looking up.',
        '"Leo felt angry."',
        '"He was very, very angry."',
      ],
      correctIndex: 1,
      hint: 'Show don\'t tell — body language and tone reveal emotion.',
      difficulty: 3,
      imageEmoji: '💢',
    ),
    StoryQuestion(
      id: 'ss_dia_5',
      skillId: 'skill_dialogue_creation',
      question: 'Which dialogue is punctuated CORRECTLY?',
      options: [
        '"I love Tim Tams", said Priya.',
        '"I love Tim Tams," said Priya.',
        '"I love Tim Tams" Said Priya.',
        '"I love Tim Tams." said Priya.',
      ],
      correctIndex: 1,
      hint: 'The comma goes INSIDE the closing quote mark when followed by a dialogue tag.',
      difficulty: 3,
      imageEmoji: '🍫',
    ),
    StoryQuestion(
      id: 'ss_dia_6',
      skillId: 'skill_dialogue_creation',
      question: 'A proud character who has just won the swimming nationals would most likely say:',
      options: [
        '"I guess I sort of won or something."',
        '"I AM THE CHAMPION! I trained every day and it paid off!"',
        '"Whatever. It was just a swim."',
        '"I didn\'t really try."',
      ],
      correctIndex: 1,
      hint: 'Dialogue should match a character\'s personality and current emotional state.',
      difficulty: 3,
      imageEmoji: '🏅',
    ),
    StoryQuestion(
      id: 'ss_dia_7',
      skillId: 'skill_dialogue_creation',
      question: 'Two characters sit in silence, then one says "Nice weather." They both know the other is moving overseas tomorrow. What does this dialogue show?',
      options: [
        'They are genuinely interested in the weather',
        'Subtext — they are avoiding the real topic because it is too painful',
        'They are bored',
        'They have nothing in common',
      ],
      correctIndex: 1,
      hint: 'What they DON\'T say is more important than what they do say.',
      difficulty: 4,
      imageEmoji: '🌧️',
    ),
  ];

  static const List<StoryQuestion> _plotQuestions = [
    StoryQuestion(
      id: 'ss_plot_1',
      skillId: 'skill_plot_structure',
      question: 'What is the CLIMAX of a story?',
      options: ['The very beginning', 'The most exciting part', 'The final page', 'The table of contents'],
      correctIndex: 1,
      hint: 'The part where everything happens!',
      difficulty: 3,
      imageEmoji: '🌋',
    ),
    StoryQuestion(
      id: 'ss_plot_2',
      skillId: 'skill_plot_structure',
      question: 'In "The Boy Who Cried Wolf," what was the RESOLUTION?',
      options: ['He lied about the wolf', 'The wolf finally came', 'The boy learned to tell the truth', 'He ate lunch'],
      correctIndex: 2,
      hint: 'The lesson or the end of the problem.',
      difficulty: 3,
      imageEmoji: '🐺',
    ),
    StoryQuestion(
      id: 'ss_plot_3',
      skillId: 'skill_plot_structure',
      question: 'Which element starts the adventure in a story?',
      options: ['The Middle', 'The Inciting Incident', 'The Resolution', 'The Glossary'],
      correctIndex: 1,
      hint: 'The spark that starts the flame.',
      difficulty: 3,
      imageEmoji: '🧨',
    ),
    StoryQuestion(
      id: 'ss_plot_4',
      skillId: 'skill_plot_structure',
      question: 'In most adventure stories, the CONFLICT drives the plot. A conflict is...',
      options: [
        'A type of character',
        'The problem or struggle the main character faces',
        'The happy ending',
        'The setting of the story',
      ],
      correctIndex: 1,
      hint: 'It\'s the central struggle that keeps readers turning pages.',
      difficulty: 2,
      imageEmoji: '⚔️',
    ),
    StoryQuestion(
      id: 'ss_plot_5',
      skillId: 'skill_plot_structure',
      question: 'After the inciting incident, the story enters the RISING ACTION. What happens here?',
      options: [
        'The problem is solved immediately',
        'The character faces a series of challenges that build toward the climax',
        'The story ends quietly',
        'New characters replace the original ones',
      ],
      correctIndex: 1,
      hint: 'Think of it as building tension, like climbing a hill before the peak.',
      difficulty: 3,
      imageEmoji: '📈',
    ),
    StoryQuestion(
      id: 'ss_plot_6',
      skillId: 'skill_plot_structure',
      question: 'An author writes early in the book: "Marco tucked the old key into his pocket, not yet knowing it would unlock a secret that changed everything." This is...',
      options: [
        'A flashback to earlier events',
        'Foreshadowing — a hint about something important to come',
        'The resolution of the main conflict',
        'A character description',
      ],
      correctIndex: 1,
      hint: 'The author is planting a clue for later.',
      difficulty: 4,
      imageEmoji: '🔑',
    ),
    StoryQuestion(
      id: 'ss_plot_7',
      skillId: 'skill_plot_structure',
      question: 'A story is about a young girl who learns that helping her community is more important than being famous. This underlying message is the story\'s...',
      options: [
        'Setting',
        'Climax',
        'Theme',
        'Genre',
      ],
      correctIndex: 2,
      hint: 'It\'s the big idea or life lesson the whole story sends.',
      difficulty: 4,
      imageEmoji: '💡',
    ),
  ];

  static const List<StoryQuestion> _descriptionQuestions = [
    StoryQuestion(
      id: 'ss_desc_1',
      skillId: 'skill_descriptive_language',
      question: 'Which adjective best describes the Great Barrier Reef?',
      options: ['Vibrant & Colorful', 'Grey & Dull', 'Boring', 'Empty'],
      correctIndex: 0,
      hint: 'Think of all the fish and coral!',
      difficulty: 1,
      imageEmoji: '🐠',
    ),
    StoryQuestion(
      id: 'ss_desc_2',
      skillId: 'skill_descriptive_language',
      question: 'Complete the sentence with a vivid word: The outback sun was...',
      options: ['blistering', 'nice', 'okay', 'blue'],
      correctIndex: 0,
      hint: 'It is very, very hot!',
      difficulty: 2,
      imageEmoji: '☀️',
    ),
    StoryQuestion(
      id: 'ss_desc_3',
      skillId: 'skill_descriptive_language',
      question: 'Choose the best descriptive sentence:',
      options: [
        'The water was blue.',
        'The turquoise waves crashed against the jagged, grey rocks.',
        'The waves were big.',
        'It was salty.'
      ],
      correctIndex: 1,
      hint: 'Use more detail!',
      difficulty: 3,
      imageEmoji: '🌊',
    ),
    StoryQuestion(
      id: 'ss_desc_4',
      skillId: 'skill_descriptive_language',
      question: 'Which sentence uses a METAPHOR to describe the Sydney Harbour?',
      options: [
        'The harbour was very big and blue.',
        'The harbour was like a huge mirror.',
        'The harbour was a glittering jewel cradled by the city.',
        'The harbour had lots of boats.',
      ],
      correctIndex: 2,
      hint: 'A metaphor says something IS something else — no "like" or "as".',
      difficulty: 3,
      imageEmoji: '🌉',
    ),
    StoryQuestion(
      id: 'ss_desc_5',
      skillId: 'skill_descriptive_language',
      question: 'Which sentence gives the wind a HUMAN quality (personification)?',
      options: [
        'The wind was very strong.',
        'The wind blew hard all day.',
        'The wind howled and screamed through the gum trees.',
        'There was a lot of wind.',
      ],
      correctIndex: 2,
      hint: 'Can wind actually howl and scream?',
      difficulty: 3,
      imageEmoji: '💨',
    ),
    StoryQuestion(
      id: 'ss_desc_6',
      skillId: 'skill_descriptive_language',
      question: 'Which sentence uses the most senses to describe a bushfire warning day?',
      options: [
        'It was hot.',
        'The sky was orange.',
        'The scorching air tasted of ash, the distant smoke stung their eyes, and they heard distant crackling.',
        'It was dangerous.',
      ],
      correctIndex: 2,
      hint: 'Good description uses sight, smell, taste, touch, and sound.',
      difficulty: 4,
      imageEmoji: '🔥',
    ),
    StoryQuestion(
      id: 'ss_desc_7',
      skillId: 'skill_descriptive_language',
      question: 'Which word choice creates the most TENSION in this sentence about a crocodile?\n\n"The crocodile _____ through the water."',
      options: ['swam', 'moved', 'slid', 'glided silently'],
      correctIndex: 3,
      hint: 'Which word sounds most threatening and stealthy?',
      difficulty: 4,
      imageEmoji: '🐊',
    ),
  ];
}
